/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface TranslationSet {
  // Navigation
  navHome: string;
  navAbout: string;
  navServices: string;
  navBeforeAfter: string;
  navDoctors: string;
  navContact: string;
  navBookBtn: string;
  navTitle: string;
  navSubtitle: string;

  // Hero Section
  heroBadge: string;
  heroHeading: string;
  heroHeadingAccent: string;
  heroDesc: string;
  heroCtaBook: string;
  heroCtaAiScan: string;

  // Stats Section
  statsSatisfied: string;
  statsSuccess: string;
  statsSurgeons: string;
  statsExperience: string;

  // Video Section
  videoTitle: string;
  videoDuration: string;

  // About Section
  aboutBadge: string;
  aboutHeading: string;
  aboutDesc: string;
  aboutPoint1: string;
  aboutPoint1Desc: string;
  aboutPoint2: string;
  aboutPoint2Desc: string;
  aboutPoint3: string;
  aboutPoint3Desc: string;

  // Services Section
  servicesBadge: string;
  servicesHeading: string;
  servicesDesc: string;
  service1Title: string;
  service1Desc: string;
  service2Title: string;
  service2Desc: string;
  service3Title: string;
  service3Desc: string;
  service4Title: string;
  service4Desc: string;

  // Treatment Journey
  journeyBadge: string;
  journeyHeading: string;
  journeyStep1: string;
  journeyStep1Desc: string;
  journeyStep2: string;
  journeyStep2Desc: string;
  journeyStep3: string;
  journeyStep3Desc: string;
  journeyStep4: string;
  journeyStep4Desc: string;

  // Before & After Gallery
  baBadge: string;
  baHeading: string;
  baDesc: string;
  baRating: string;
  baStoryLabel: string;
  baCase1Title: string;
  baCase1Desc: string;
  baCase1Story: string;
  baCase1Type: string;
  baCase1Duration: string;
  baCase2Title: string;
  baCase2Desc: string;
  baCase2Story: string;
  baCase2Type: string;
  baCase2Duration: string;
  baCase3Title: string;
  baCase3Desc: string;
  baCase3Story: string;
  baCase3Type: string;
  baCase3Duration: string;

  // AI Diagnosis Section
  aiBadge: string;
  aiHeading: string;
  aiHeadingAccent: string;
  aiDesc: string;
  aiUploadTitle: string;
  aiUploadDesc: string;
  aiUploadDrop: string;
  aiCameraBtn: string;
  aiScanningTitle: string;
  aiScanningDesc: string;
  aiScoreLabel: string;
  aiScoreStatus: string;
  aiNewScan: string;
  aiFindingsTitle: string;
  aiRecsLabel: string;
  aiClinicPlan: string;
  aiShareTitle: string;
  aiShareDesc: string;
  aiShareBtn: string;
  aiConf: string;

  // Emergency Mode Dialog
  emTitle: string;
  emDesc: string;
  emCtaBook: string;
  emCtaWhatsapp: string;
  emSimulationBtn: string;

  // Doctors Section
  docBadge: string;
  docHeading: string;
  docDesc: string;
  doc1Name: string;
  doc1Spec: string;
  doc1Desc: string;
  doc2Name: string;
  doc2Spec: string;
  doc2Desc: string;

  // Darija Reviews
  reviewBadge: string;
  reviewHeading: string;
  review1Text: string;
  review2Text: string;

  // Location / Earth Finder
  earthBadge: string;
  earthHeading: string;
  earthDesc: string;
  earthMapText: string;

  // Blog Section
  blogBadge: string;
  blogHeading: string;
  blogDesc: string;
  blogReadMore: string;
  blogArt1Title: string;
  blogArt1Desc: string;
  blogArt1Cat: string;
  blogArt2Title: string;
  blogArt2Desc: string;
  blogArt2Cat: string;
  blogArt3Title: string;
  blogArt3Desc: string;
  blogArt3Cat: string;

  // Contact Form / Scheduler
  contactBadge: string;
  contactHeading: string;
  contactDesc: string;
  formName: string;
  formPhone: string;
  formService: string;
  formServiceSelect: string;
  formDate: string;
  formBookBtn: string;
  successMsg: string;
  errorMsg: string;

  // Footer & Misc
  footerSlogan: string;
  footerMap: string;
  footerSupport: string;
  footerRights: string;
  footerLabel: string;
}

export const translations: Record<string, TranslationSet> = {
  ar: {
    navHome: "الرئيسية", navAbout: "عن العيادة", navServices: "الخدمات", navBeforeAfter: "قبل وبعد", navDoctors: "الأطباء", navContact: "اتصل بنا", navBookBtn: "احجز موعدك", navTitle: "ابتسامة", navSubtitle: "عيادات الأسنان الفاخرة",
    heroBadge: "ثورة طب الأسنان الرقمي والجمال الماسي", heroHeading: "مستقبل تصميم الابتسامات", heroHeadingAccent: "بأيدي علمية فائقة الدقة", heroDesc: "عيادة د. أحمد هندية الأولى في الشرق الأوسط التي تدمج الذكاء الاصطناعي مع زراعة وتجميل الأسنان المجهري لنضمن لك ابتسامة مثالية وصحة مستدامة وبدون ألم.", heroCtaBook: "ابدأ رحلتك الآن", heroCtaAiScan: "فحص فوري بالذكاء الاصطناعي",
    statsSatisfied: "عميل يبتسم بثقة", statsSuccess: "نسبة نجاح العمليات المعقدة", statsSurgeons: "أطباء وجراحين عالميين", statsExperience: "عاماً من التميز الطبي والبحثي",
    videoTitle: "شاهد مختبرنا وجولتك الطبية التجميلية", videoDuration: "فيديو العيادة (01:45)",
    aboutBadge: "منظومة طبية فائقة التطور", aboutHeading: "عيادة د. أحمد هندية.. الابتسامة كشفرة جينية فريدة", aboutDesc: "نحن لا نطبق قوالب جاهزة؛ بل ندرس شكل الوجه وبصمة الشفاه والفكين لنصنع ابتسامة تنسجم معك تماماً.", aboutPoint1: "توجيه جراحي بالكمبيوتر", aboutPoint1Desc: "زراعة أسنان رقمية موجهة بالكامل تضمن دقة 100% بدون شق جراحي أو ألم.", aboutPoint2: "تكنولوجيا الـ CAD/CAM", aboutPoint2Desc: "تصميم وصناعة عدسات الفينير والتيجان الفاخرة في جلسة واحدة مريحة وبأقصى درجات الطبيعية.", aboutPoint3: "فحص ميكروسكوبي مجهري", aboutPoint3Desc: "علاج القنوات وحشوات الأسنان تحت الميكروسكوب لضمان أعلى مستويات الأمان والديمومة.",
    servicesBadge: "باقة الخدمات الطبية التجميلية الفاخرة", servicesHeading: "أحدث الحلول العلاجية بلمسة تكنولوجية", servicesDesc: "خدمات تخصصية مصممة بعناية فائقة لتلبي أعلى تطلعات الجمال والراحة والصحة المستدامة.", service1Title: "عدسات الفينير الرقيقة والزيركون واللومينير", service1Desc: "تصميم ابتسامة هوليود الماسية بعدسات رقيقة تحتفظ بلونها وتتحمل كلياً.", service2Title: "الزراعة الفورية بمساعدة الكمبيوتر", service2Desc: "تعويض الأسنان المفقودة بجلسة واحدة دون شق جراحي وبأحدث الغرسات.", service3Title: "تقويم الأسنان الشفاف (Invisalign)", service3Desc: "محاذاة هندسية دقيقة بمسارات شفافة لا يراها أحد وقابلة للإزالة لتستمتع بطعامك.", service4Title: "علاج اللثة وتجميل حوافها بالليزر المائي", service4Desc: "إصلاح الابتسامة اللثوية وتوريد اللثة الحساسة والتطهير العميق بلمسة الليزر اللطيفة وبدون ألم.",
    journeyBadge: "دليلك لابتسامة أحلامك الماسية", journeyHeading: "رحلة علاجية مريحة تعيد لك ثقتك", journeyStep1: "فحص وتصوير هولوغرافي", journeyStep1Desc: "لقطات فوتوغرافية وأشعة مقطعية لبناء خطة علاج ثلاثية الأبعاد بدقة بالغة.", journeyStep2: "محاكاة ذكاء اصطناعي فورية", journeyStep2Desc: "تطوير ومعاينة حية لشكل ابتسامتك النهائية وتعديلها لتناسب ملامحك بدقة.", journeyStep3: "التنفيذ الفائق بلمسة الليزر", journeyStep3Desc: "تحضير مجهري وعلاج آمن بأيدي الخبراء دون أي شعور بالألم أو القلق.", journeyStep4: "استلام وضمان مدى الحياة", journeyStep4Desc: "الحصول على الابتسامة الموعودة مع وثيقة ضمان طبي لراحة بال تامة.",
    baBadge: "نتائج حقيقية قبل وبعد العلاج", baHeading: "حالات واقعية تحولت إلى تحف فنية", baDesc: "اسحب المقبض المضيء في المنتصف لمشاهدة الدقة الميكروسكوبية والهندسة الطبية الفائقة لتصميمات الابتسامة.", baRating: "خمس نجوم", baStoryLabel: "قصة المريض:",
    baCase1Title: "عدسات الزيركون التجميلية الفاخرة", baCase1Desc: "تصميم الابتسامة وتعديل اصطفاف الفكين لعلاج الاصفرار الشديد والفراغات السلبية.", baCase1Story: "كانت المريضة تعاني من فقدان الثقة بسبب فراغات واصفرار حاد في الثنايا العلوية. تم تركيب 8 عدسات زيركون تجميلية بانسجام كامل مع ملامحها الطبيعية.", baCase1Type: "عدسات زيركون متطابقة طيفياً", baCase1Duration: "جلستان (5 أيام)",
    baCase2Title: "زراعة الأسنان الفورية الرقمية", baCase2Desc: "تعويض الضواحك المفقودة وتثبيت فوري متين يعيد وظيفة المضغ الطبيعي بالكامل.", baCase2Story: "فقدان مفاجئ للضرس الطاحن السفلي الأيسر. تم تطبيق الزراعة الفورية الموجهة رقمياً بجلسة واحدة مدتها 45 دقيقة دون أي شق جراحي أو خياطة.", baCase2Type: "غرسة تيتانيوم سويسرية نانوية", baCase2Duration: "جلسة واحدة (ساعتين)",
    baCase3Title: "تقويم الأسنان الشفاف غير المرئي", baCase3Desc: "تصحيح الازدحام الشديد وتراكب الأسنان في فترات قياسية وبمظهر مريح غير ملحوظ.", baCase3Story: "ازدحام وتراكب واضح بالأسنان العلوية والسفلية. بفضل قوالب Invisalign المصنوعة بالذكاء الاصطناعي، تم تصحيح الارتصاف والمحاذاة خلال 6 أشهر.", baCase3Type: "تقويم Invisalign الذكي ثلاثي الأبعاد", baCase3Duration: "6 أشهر فقط",
    aiBadge: "مركز الذكاء الاصطناعي لتحليل الأسنان", aiHeading: "تحليل ذكي فوري لصحة", aiHeadingAccent: "وابتسامة أسنانك", aiDesc: "ادخل إلى مختبر التشخيص الهولوغرافي المستقبلي. ارفع لقطة لأنفاسك أو ابتسامتك، ليعمل عقلنا الاصطناعي الطبي الفائق على فحص سلامتها وتوليد نماذج تشريحية متطورة بلمحة بصر.", aiUploadTitle: "قم برفع صورة واضحة لأسنانك ليقوم موقعنا بتحليلها", aiUploadDesc: "يدعم الذكاء الاصطناعي صيغ الصور عالية الدقة. يرجى التأكد من توفر إضاءة جيدة وتصوير الفكين بشكل مقابل.", aiUploadDrop: "اسحب صورتك الطبية وأفلتها هنا أو اضغط للاختيار", aiCameraBtn: "التقاط لقطة فورية (محاكي الكاميرا)", aiScanningTitle: "معالجة الذكاء الاصطناعي قيد التشغيل", aiScanningDesc: "جاري فحص كثافة المينا وتحليل اللثة وصياغة التوصيات الطبية الفورية...", aiScoreLabel: "درجة صحة الأسنان العامة", aiScoreStatus: "ممتازة وخاضعة للمراقبة", aiNewScan: "إعادة فحص جديد", aiFindingsTitle: "الملاحظات والمؤشرات الطبية المكتشفة (انقر للتركيز):", aiRecsLabel: "التوصيات الطبية المقترحة بواسطة الذكاء الاصطناعي:", aiClinicPlan: "الخطة العلاجية والخدمات المقترحة بالمستشفى:", aiShareTitle: "شارك التقرير مباشرة مع الطبيب", aiShareDesc: "أرسل النتائج الفورية للعيادة لحجز استشارة مخصصة بضغطة واحدة.", aiShareBtn: "إرسال التقرير وحجز موعد عبر الواتساب", aiConf: "تأكيد",
    emTitle: "⚠️ حالة الأسنان تتطلب تدخلاً عاجلاً", emDesc: "اكتشف الذكاء الاصطناعي وجود مشاكل خطيرة في الأسنان. ننصح بحجز موعد في أقرب وقت لتجنب تفاقم الحالة.", emCtaBook: "احجز موعداً الآن", emCtaWhatsapp: "التواصل عبر واتساب", emSimulationBtn: "رفع صورة حالة حرجة (محاكاة الطوارئ)",
    docBadge: "نخبة الأطباء والجراحين الأخصائيين", docHeading: "خبرة عالمية مكرسة لجمال ابتسامتك", docDesc: "طاقمنا الطبي يضم كبار الاختصاصيين خريجي الجامعات الأوروبية والأمريكية بخبرة تفوق 15 عاماً.", doc1Name: "د. أحمد هندية", doc1Spec: "استشاري زراعة وتجميل الأسنان المجهري", doc1Desc: "خبير رائد في الابتسامات الماسية الرقمية وتصميم الابتسامة بمساعدة الكمبيوتر.", doc2Name: "د. ياسمين المرابط", doc2Spec: "أخصائية تقويم الأسنان وجراحة الفكين", doc2Desc: "خبيرة معتمدة دولياً في تقويم الأسنان الشفاف وتصحيح العضة الهندسية ثلاثية الأبعاد.",
    reviewBadge: "تقييمات مريضانا بلهجات حقيقية", reviewHeading: "تجارب وقصص مريضانا في العيادة", review1Text: "الصراحة عمري ما شفت بحال هاد المعاملة وهاد التكنولوجيا الفايتة وقتها! النتيجة طالعة واعرة وبلا حريق.", review2Text: "أحسن عيادة في المغرب والشرق الأوسط، الفينير طالع طبيعي بزاف وكلشي تيسولني عليه. شكرا بزاف دكتور أحمد هندية.",
    earthBadge: "موقعنا الاستراتيجي وتغطيتنا الدولية", earthHeading: "أينما كنت.. نسهل وصولك للابتسامة", earthDesc: "نستقبل مرضانا من كافة دول الخليج وأوروبا ونوفر لهم خدمات نقل مجانية وإقامة فاخرة.", earthMapText: "الموقع الرئيسي: الدار البيضاء، المغرب - شارع النخيل - الطابق 3",
    blogBadge: "آخر مستجدات عالم تجميل وصحة الأسنان", blogHeading: "المدونة الطبية والمعرفية المتخصصة", blogDesc: "مقالات علمية مبسطة ونصائح وقائية يكتبها خبراؤنا لتستمتع بأسنان صحية وابتسامة ساحرة مدى الحياة.", blogReadMore: "اقرأ المقال كاملاً",
    blogArt1Title: "تصميم الابتسامة ثلاثي الأبعاد CAD/CAM: كيف تعمل التكنولوجيا؟", blogArt1Desc: "اكتشف كيف نقوم بتصميم عدسات الأسنان المخصصة في جلسة واحدة بأعلى دقة ميكرومترية تناسب معالم وجهك.", blogArt1Cat: "تكنولوجيا تجميلية",
    blogArt2Title: "زراعة الأسنان بدون جراحة وبدون ألم: حقيقة أم مجرد دعاية؟", blogArt2Desc: "ندرس بالتفصيل كيف تساهم أدلة التوجيه الرقمي في تفادي العمليات الجراحية الطويلة وجعلك تغادر بضرس كامل.", blogArt2Cat: "جراحة وزراعة",
    blogArt3Title: "كيف تختار عدسات الفينير المناسبة لك: الزيركون أم اللومينير؟", blogArt3Desc: "دليلك الطبي الشامل للفروقات الهيكلية والجمالية بين أنواع عدسات الأسنان لتتخذ القرار الصحيح لابتسامتك.", blogArt3Cat: "تجميل الأسنان",
    contactBadge: "بوابة الحجز الطبي وجدولة الاستشارات الفورية", contactHeading: "ابدأ رحلة التغيير واحجز مقعدك اليوم", contactDesc: "املأ البيانات البسيطة أدناه ليقوم مساعدنا الذكي بالتحقق وتوليد تذكرة الدخول المباشر للعيادة.", formName: "الاسم الكامل للمريض", formPhone: "رقم الهاتف (مع رمز الدولة)", formService: "الخدمة الطبية المطلوبة", formServiceSelect: "اختر الخدمة...", formDate: "تاريخ الموعد المفضل", formBookBtn: "تأكيد طلب الحجز وإصدار التذكرة", successMsg: "تم تسجيل حجزك وتوليد التذكرة بنجاح! سيتم التواصل معك فوراً.", errorMsg: "يرجى تعبئة كافة الحقول بشكل صحيح لإصدار التذكرة.",
    footerSlogan: "منصة الرعاية الصحية التجميلية الرائدة لطب وزراعة الأسنان في الشرق الأوسط. نحن نصمم الفرحة ونعيد ابتكار الجمال الطبي بأحدث أدوات التكنولوجيا والذكاء الاصطناعي.", footerMap: "خريطة المنصة", footerSupport: "الشؤون الطبية", footerRights: "حقوق الطبع محفوظة © 2026 عيادات ابتسامة الرقمية.", footerLabel: "معتمد دولياً ومتاح 24/7"
  },
  en: {
    navHome: "Home", navAbout: "About Us", navServices: "Services", navBeforeAfter: "Before & After", navDoctors: "Doctors", navContact: "Contact", navBookBtn: "Book Appointment", navTitle: "Smile", navSubtitle: "Luxury Dental Clinics",
    heroBadge: "Digital Dentistry Revolution & Diamond Smile", heroHeading: "The Future of Smile Design", heroHeadingAccent: "With Surgical Precision", heroDesc: "Dr. Ahmed Hendia's clinic is the first in the Middle East to integrate artificial intelligence with microscopic dental implantology and cosmetics, ensuring a perfect smile painlessly.", heroCtaBook: "Start Your Journey", heroCtaAiScan: "Instant AI Dental Scan",
    statsSatisfied: "Patients Smiling Confidently", statsSuccess: "Success Rate in Complex Surgeries", statsSurgeons: "International Expert Surgeons", statsExperience: "Years of Medical & Research Excellence",
    videoTitle: "Watch Our Lab & Take a Virtual Tour", videoDuration: "Clinic Tour Video (01:45)",
    aboutBadge: "Highly Advanced Medical System", aboutHeading: "Dr. Ahmed Hendia's Clinic... Your Smile as a Unique Genetic Code", aboutDesc: "We do not apply ready-made templates; instead, we study your facial structure, lip dynamics, and jaws to engineer a smile that harmonizes with your essence.", aboutPoint1: "Computer-Guided Surgery", aboutPoint1Desc: "Fully guided dental implants that ensure 100% accuracy without painful surgical cuts.", aboutPoint2: "CAD/CAM Technology", aboutPoint2Desc: "Design and fabrication of premium veneers and crowns in a single comfortable session with ultra-natural look.", aboutPoint3: "Microscopic Dental Examination", aboutPoint3Desc: "Root canal therapy and dental restorations under high-resolution microscopes for absolute safety.",
    servicesBadge: "Luxury Cosmetic Dentistry Portfolio", servicesHeading: "State-of-the-Art Treatment with a Tech Touch", servicesDesc: "Specialized services meticulously designed to meet the highest aspirations of beauty, comfort, and dental longevity.", service1Title: "Zirconia, Lumineers & Ultra-Thin Veneers", service1Desc: "Get your diamond Hollywood Smile with thin, stain-resistant veneers that withstand forces.", service2Title: "Computer-Guided Immediate Implants", service2Desc: "Replace missing teeth in a single session without surgical cuts using high-tech implants.", service3Title: "Invisalign (Invisible Braces)", service3Desc: "Perfect alignment using customized clear trays that are removable and completely invisible.", service4Title: "Laser Gum Treatment & Contouring", service4Desc: "Repair gummy smiles, depigment sensitive gums, and enjoy painless deep disinfection using gentle lasers.",
    journeyBadge: "Your Guide to a Diamond Dream Smile", journeyHeading: "A Comfortable Healing Journey Built Around You", journeyStep1: "Holographic Diagnosis", journeyStep1Desc: "Advanced 3D CT scans and photographic mapping to design a perfect micro-precision treatment path.", journeyStep2: "Live AI Simulation", journeyStep2Desc: "Instant interactive 3D rendering of your proposed smile to inspect and tweak details beforehand.", journeyStep3: "Surgical Micro-Execution", journeyStep3Desc: "Painless laser treatment and precise restoration by international experts with zero discomfort.", journeyStep4: "Lifetime Smile & Guarantee", journeyStep4Desc: "Unveil your beautiful new smile backed by a durable medical warranty certificate for peace of mind.",
    baBadge: "Real Before & After Treatment Cases", baHeading: "Real Patients, Real Masterpieces", baDesc: "Drag the shining slider handle in the center to witness the microscopic precision and medical engineering of our designs.", baRating: "Five Stars", baStoryLabel: "Patient Story:",
    baCase1Title: "Premium Cosmetic Zirconia Veneers", baCase1Desc: "Smile design and jaw alignment correcting severe yellowing and negative diastemas.", baCase1Story: "The patient suffered from severe diastema and teeth yellowing, affecting her self-confidence. 8 bespoke Zirconia veneers were fabricated to blend with her features.", baCase1Type: "Spectrally Matched Zirconia Veneers", baCase1Duration: "2 sessions (5 days)",
    baCase2Title: "Computer-Guided Immediate Implants", baCase2Desc: "Replacing missing premolars with strong, functional crowns that fully restore natural chewing.", baCase2Story: "Sudden loss of lower left molar. Digitally guided dental implants were placed in a single 45-minute session without painful incisions or sutures.", baCase2Type: "Swiss Nanostructured Titanium Implant", baCase2Duration: "1 session (2 hours)",
    baCase3Title: "Invisalign Invisible Orthodontics", baCase3Desc: "Correcting severe crowding and crooked teeth within record times in a comfortable, stealthy manner.", baCase3Story: "Crowded upper and lower incisors. Utilizing custom AI-designed Invisalign aligners, tooth alignment was perfectly completed in just 6 months.", baCase3Type: "Custom 3D Invisalign System", baCase3Duration: "6 months only",
    aiBadge: "AI Dental Diagnosis Hub", aiHeading: "Instant Smart Analysis for Your", aiHeadingAccent: "Dental Health & Smile", aiDesc: "Step into our future diagnostic holographic laboratory. Upload a picture of your smile, and our medical supercomputer will inspect it and generate anatomical feedback in seconds.", aiUploadTitle: "Upload a Clear Photo of Your Teeth for AI Analysis", aiUploadDesc: "The AI supports high-resolution formats. Please ensure adequate lighting and capturing a straight-on view.", aiUploadDrop: "Drag and drop your dental photo here or click to choose", aiCameraBtn: "Capture Instant Photo (Camera Simulator)", aiScanningTitle: "AI Diagnostics Active", aiScanningDesc: "Inspecting enamel density, analyzing gum tissue, and generating instant clinical recommendations...", aiScoreLabel: "Overall Dental Health Score", aiScoreStatus: "Excellent & Supervised", aiNewScan: "Start New Scan", aiFindingsTitle: "Detected Findings (Click to inspect):", aiRecsLabel: "AI Recommended Action Plan:", aiClinicPlan: "Proposed Treatment Path in Clinic:", aiShareTitle: "Share the Report Directly with Your Doctor", aiShareDesc: "Send instant results to our clinic to book a personalized consultation with a single tap.", aiShareBtn: "Send Report & Book on WhatsApp", aiConf: "Confidence",
    emTitle: "⚠️ Critical Condition Detected!", emDesc: "The AI has detected urgent dental issues that require immediate attention. We recommend scheduling an appointment as soon as possible to prevent complications.", emCtaBook: "Book Appointment Now", emCtaWhatsapp: "Contact via WhatsApp", emSimulationBtn: "Upload Critical Case (Emergency Simulation)",
    docBadge: "Elite Medical Specialists & Surgeons", docHeading: "Global Experience Dedicated to Your Smile", docDesc: "Our medical staff includes world-renowned specialists, graduates of premium European and American universities, with 15+ years of experience.", doc1Name: "Dr. Ahmed Hendia", doc1Spec: "Consultant in Microscopic & Implant Dentistry", doc1Desc: "Pioneer in digital diamond smiles and computer-aided aesthetic reconstruction.", doc2Name: "Dr. Yasmine El Morabit", doc2Spec: "Orthodontics & Maxillofacial Specialist", doc2Desc: "Internationally certified expert in Invisalign clear aligners and 3D bite correction.",
    reviewBadge: "Patient Reviews with Authentic Voices", reviewHeading: "Real Healing Stories from Our Patients", review1Text: "Honestly, I have never seen such care and futuristic technology! The result is amazing and completely painless.", review2Text: "Best dental clinic in Morocco and the Middle East. The veneers look incredibly natural, everyone asks me about them. Thank you, Dr. Hendia!",
    earthBadge: "Our Strategic Location & International Support", earthHeading: "Wherever You Are, Your Diamond Smile is Within Reach", earthDesc: "We welcome patients from all over Europe and the Gulf, providing complimentary private airport transfers and luxury hotel stays.", earthMapText: "Main HQ: Palm Avenue, Floor 3, Casablanca, Morocco",
    blogBadge: "Latest Developments in Dental Aesthetics & Care", blogHeading: "The Specialized Dental Medical Blog", blogDesc: "Scientific insights, tips, and preventive articles written by our leading specialists to help you keep a radiant smile.", blogReadMore: "Read Full Article",
    blogArt1Title: "3D CAD/CAM Smile Design: How Does It Work?", blogArt1Desc: "Discover how we fabricate customized dental crowns and veneers in a single session with micro-precision fitting your facial architecture.", blogArt1Cat: "Aesthetic Tech",
    blogArt2Title: "Painless Dental Implants Without Surgery: Fact or Fiction?", blogArt2Desc: "A detailed medical look at how digital surgical guides avoid large cuts, allowing you to walk home with complete implants on the same day.", blogArt2Cat: "Surgical Care",
    blogArt3Title: "How to Choose the Right Veneers: Zirconia or Lumineers?", blogArt3Desc: "A comprehensive clinical guide covering aesthetic and structural differences to help you make the perfect decision for your smile.", blogArt3Cat: "Cosmetics",
    contactBadge: "Booking Portal & Instant Consultation Scheduler", contactHeading: "Embrace the Change and Reserve Your Spot Today", contactDesc: "Fill in your details below. Our AI assistant will verify open spots and generate your direct entry pass.", formName: "Full Patient Name", formPhone: "Phone Number (with country code)", formService: "Requested Treatment Category", formServiceSelect: "Select a service...", formDate: "Preferred Appointment Date", formBookBtn: "Confirm Booking & Issue Entry Pass", successMsg: "Your booking request is received! Your secure entry ticket is generated successfully.", errorMsg: "Please fill out all required fields correctly to issue your pass.",
    footerSlogan: "The Middle East's premier digital dental center. We design joy and reinvent natural aesthetics using artificial intelligence and computer-guided microscopic surgery.", footerMap: "Platform Map", footerSupport: "Medical Affairs", footerRights: "All Rights Reserved © 2026 Smile Digital Clinics.", footerLabel: "Internationally Certified & Available 24/7"
  },
  fr: {
    navHome: "Accueil", navAbout: "À Propos", navServices: "Services", navBeforeAfter: "Avant / Après", navDoctors: "Médecins", navContact: "Contact", navBookBtn: "Prendre RDV", navTitle: "Smile", navSubtitle: "Cliniques Dentaires de Luxe",
    heroBadge: "Révolution Dentaire Numérique & Sourire Diamant", heroHeading: "Le Futur du Design de Sourire", heroHeadingAccent: "Avec une Précision Chirurgicale", heroDesc: "La clinique du Dr Ahmed Hendia est la première au Moyen-Orient à intégrer l'intelligence artificielle à l'implantologie microscopique et esthétique, assurant un sourire parfait sans douleur.", heroCtaBook: "Commencer l'Aventure", heroCtaAiScan: "Analyse Instantanée par IA",
    statsSatisfied: "Patients Souriant avec Confiance", statsSuccess: "Taux de Réussite des Chirurgies Complexes", statsSurgeons: "Chirurgiens Experts Internationaux", statsExperience: "Années d'Excellence Médicale",
    videoTitle: "Visitez Notre Laboratoire Futuriste", videoDuration: "Vidéo Clinique (01:45)",
    aboutBadge: "Système Médical Ultra-Avancé", aboutHeading: "Clinique Dr Ahmed Hendia... Votre Sourire comme Code Génétique Unique", aboutDesc: "Nous n'appliquons pas de modèles génériques ; nous étudions votre visage, vos lèvres et vos mâchoires pour concevoir un sourire sur mesure.", aboutPoint1: "Chirurgie Guidée par Ordinateur", aboutPoint1Desc: "Implants dentaires guidés à 100% assurant une précision absolue sans incisions douloureuses.", aboutPoint2: "Technologie CAD/CAM", aboutPoint2Desc: "Conception et fabrication de facettes en une seule séance pour un aspect ultra-naturel.", aboutPoint3: "Examen Microscopique", aboutPoint3Desc: "Traitement de canal sous microscope pour une sécurité et une longévité absolues.",
    servicesBadge: "Portefeuille de Dentisterie Esthétique de Luxe", servicesHeading: "Traitements de Pointe avec une Touche Technologique", servicesDesc: "Services de pointe minutieusement conçus pour répondre aux plus hautes exigences de beauté et de confort.", service1Title: "Facettes de Zircone, Lumineers & Ultra-Fin", service1Desc: "Obtenez un sourire Hollywood Smile diamant avec des facettes résistantes aux taches.", service2Title: "Implants Immédiats par Ordinateur", service2Desc: "Remplacez les dents manquantes en une séance sans points de suture douloureux.", service3Title: "Invisalign (Aligneurs Invisibles)", service3Desc: "Alignement parfait avec des gouttières transparentes amovibles et indétectables.", service4Title: "Traitement des Gencives au Laser", service4Desc: "Réparez les sourires gingivaux et désinfectez sans douleur grâce au laser doux.",
    journeyBadge: "Guide vers Votre Sourire de Rêve", journeyHeading: "Un Parcours de Soins Confortable Centré sur Vous", journeyStep1: "Diagnostic Holographique", journeyStep1Desc: "Scans 3D complets pour concevoir un parcours de traitement précis au micromètre près.", journeyStep2: "Simulation IA en Direct", journeyStep2Desc: "Rendu 3D interactif instantané pour vérifier et ajuster chaque facette à l'avance.", journeyStep3: "Micro-Exécution Chirurgicale", journeyStep3Desc: "Traitements au laser indolores par nos chirurgiens pour un confort de premier ordre.", journeyStep4: "Sourire & Garantie à Vie", journeyStep4Desc: "Dévoilez votre nouveau sourire avec un certificat de garantie médicale longue durée.",
    baBadge: "Cas Réels Avant / Après Traitement", baHeading: "De Vrais Patients, de Vrais Chefs-d'œuvre", baDesc: "Glissez le bouton lumineux pour observer la précision microscopique de nos réalisations.", baRating: "Cinq Étoiles", baStoryLabel: "Histoire du Patient :",
    baCase1Title: "Facettes Cosmétiques Premium en Zircone", baCase1Desc: "Design de sourire corrigeant le jaunissement sévère et les espaces interdentaires.", baCase1Story: "La patiente souffrait de diastèmes prononcés. 8 facettes en zircone sur mesure ont été posées pour s'harmoniser parfaitement avec son visage.", baCase1Type: "Facettes en Zircone Harmonisées", baCase1Duration: "2 séances (5 jours)",
    baCase2Title: "Implants Immédiats Guidés par Ordinateur", baCase2Desc: "Remplacement de prémolaires avec des couronnes solides rétablissant la mastication naturelle.", baCase2Story: "Perte d'une molaire inférieure. Pose d'un implant guidé en une seule séance de 45 minutes sans incisions ni points de suture.", baCase2Type: "Implant en Titane Nanostructuré Suisse", baCase2Duration: "1 séance (2 heures)",
    baCase3Title: "Orthodontie Invisible Invisalign", baCase3Desc: "Correction du chevauchement dentaire en un temps record de manière confortable.", baCase3Story: "Chevauchement des incisives. Grâce aux aligneurs personnalisés Invisalign conçus par IA, l'alignement a été parfaitement corrigé en 6 mois.", baCase3Type: "Système Invisalign 3D Intelligent", baCase3Duration: "6 mois seulement",
    aiBadge: "Analyse d'Imagerie Dentaire par IA", aiHeading: "Analyse Intelligente Instantanée pour Votre", aiHeadingAccent: "Santé Dentaire & Sourire", aiDesc: "Entrez dans notre laboratoire holographique de diagnostic. Téléchargez une photo de vos dents, notre supercalculateur l'analysera en quelques secondes.", aiUploadTitle: "Téléchargez une Photo Claire de vos Dents", aiUploadDesc: "L'IA prend en charge les formats haute résolution. Assurez-vous d'avoir une bonne lumière.", aiUploadDrop: "Glissez et déposez votre photo ici ou cliquez pour choisir", aiCameraBtn: "Prendre une Photo (Simulateur de Caméra)", aiScanningTitle: "Diagnostic IA Actif", aiScanningDesc: "Analyse de la densité de l'émail, examen des gencives et génération de recommandations...", aiScoreLabel: "Score Général de Santé Dentaire", aiScoreStatus: "Excellent & Supervisé", aiNewScan: "Nouvelle Analyse", aiFindingsTitle: "Observations Détectées (Cliquez pour inspecter) :", aiRecsLabel: "Plan d'Action Recommandé par l'IA :", aiClinicPlan: "Parcours Clinique Suggéré :", aiShareTitle: "Partagez le Rapport avec Votre Médecin", aiShareDesc: "Envoyez les résultats à notre clinique pour réserver une consultation d'un seul clic.", aiShareBtn: "Partager le Rapport et Prendre RDV sur WhatsApp", aiConf: "Confiance",
    emTitle: "⚠️ Urgence Dentaire Détectée !", emDesc: "L'IA a identifié des anomalies nécessitant une prise en charge immédiate. Nous vous recommandons de prendre rendez-vous rapidement pour éviter des complications.", emCtaBook: "Prendre RDV Maintenant", emCtaWhatsapp: "Contact par WhatsApp", emSimulationBtn: "Cas Critique (Simulation d'Urgence)",
    docBadge: "Spécialistes et Chirurgiens d'Élite", docHeading: "Une Expertise Globale pour Votre Sourire", docDesc: "Notre équipe comprend des spécialistes renommés diplômés des meilleures universités d'Europe et des États-Unis.", doc1Name: "Dr. Ahmed Hendia", doc1Spec: "Consultant en Implantologie Microscopique", doc1Desc: "Pionnier du sourire diamant numérique et de la reconstruction esthétique guidée par ordinateur.", doc2Name: "Dr. Yasmine El Morabit", doc2Spec: "Spécialiste en Orthodontie & Maxillo-faciale", doc2Desc: "Experte certifiée Invisalign pour l'alignement et la correction orthodontique 3D.",
    reviewBadge: "Avis Clients Authentiques", reviewHeading: "Des Histoires de Guérison Réelles", review1Text: "Franchement, je n'ai jamais vu des soins aussi futuristes ! Le résultat est incroyable et sans aucune douleur.", review2Text: "Meilleure clinique dentaire au Maroc et au Moyen-Orient. Les facettes font très naturelles, tout le monde m'en parle !",
    earthBadge: "Localisation & Support International", earthHeading: "Où que Vous Soyez, Votre Sourire est à Portée", earthDesc: "Nous accueillons des patients d'Europe et du Golfe, avec transferts privés gratuits et hôtels de luxe.", earthMapText: "Siège principal : Boulevard des Palmiers, Casablanca, Maroc",
    blogBadge: "Dernières Nouvelles de l'Esthétique Dentaire", blogHeading: "Le Blog Médical Spécialisé", blogDesc: "Articles scientifiques simples et conseils écrits par nos plus grands experts pour un sourire radieux à vie.", blogReadMore: "Lire l'Article Complet",
    blogArt1Title: "Design de Sourire 3D CAD/CAM : Comment ça Marche ?", blogArt1Desc: "Découvrez la fabrication sur mesure de facettes et de couronnes en une séance avec une précision micrométrique.", blogArt1Cat: "Technologie Esthétique",
    blogArt2Title: "Implants Sans Douleur et Sans Chirurgie : Réalité ou Mythe ?", blogArt2Desc: "Une analyse médicale montrant comment les guides chirurgicaux numériques éliminent la douleur des incisions.", blogArt2Cat: "Soins Chirurgicaux",
    blogArt3Title: "Comment Choisir ses Facettes : Zircone ou Lumineers ?", blogArt3Desc: "Un guide clinique complet détaillant les différences pour vous aider à prendre la décision parfaite.", blogArt3Cat: "Esthétique",
    contactBadge: "Portail de Réservation & Prise de RDV Instantanée", contactHeading: "Prenez Place Aujourd'hui pour Transformer Votre Sourire", contactDesc: "Saisissez vos informations. Notre IA validera les disponibilités et créera votre ticket de consultation.", formName: "Nom Complet du Patient", formPhone: "Numéro de Téléphone (avec indicatif)", formService: "Service Clinique Souhaité", formServiceSelect: "Sélectionnez un service...", formDate: "Date de Rendez-vous Préférée", formBookBtn: "Confirmer et Générer le Ticket", successMsg: "Réservation reçue avec succès ! Votre ticket de consultation sécurisé a été généré.", errorMsg: "Veuillez remplir correctement tous les champs requis.",
    footerSlogan: "Le premier centre dentaire numérique de luxe au Moyen-Orient. Nous concevons la joie et réinventons l'esthétique par l'IA et la chirurgie guidée.", footerMap: "Plan du Site", footerSupport: "Affaires Médicales", footerRights: "Tous Droits Réservés © 2026 Smile Digital Clinics.", footerLabel: "Certifié Internationalement & Disponible 24/7"
  },
  es: {
    navHome: "Inicio", navAbout: "Nosotros", navServices: "Servicios", navBeforeAfter: "Antes / Después", navDoctors: "Médicos", navContact: "Contacto", navBookBtn: "Reservar Cita", navTitle: "Smile", navSubtitle: "Clínicas Dentales de Lujo",
    heroBadge: "Revolución Dental Digital y Sonrisa de Diamante", heroHeading: "El Futuro del Diseño de Sonrisas", heroHeadingAccent: "Con Precisión Quirúrgica", heroDesc: "La clínica del Dr. Ahmed Hendia es la primera en Oriente Medio en integrar IA con implantología microscópica, garantizando un resultado impecable sin dolor.", heroCtaBook: "Iniciar Viaje", heroCtaAiScan: "Análisis con IA Instantáneo",
    statsSatisfied: "Pacientes Sonriendo", statsSuccess: "Tasa de Éxito Quirúrgico", statsSurgeons: "Cirujanos Expertos", statsExperience: "Años de Excelencia Médica",
    videoTitle: "Visite Nuestro Laboratorio Futurista", videoDuration: "Video de la Clínica (01:45)",
    aboutBadge: "Sistema Médico Ultra Avanzado", aboutHeading: "Clínica Dr. Ahmed Hendia... Tu Sonrisa como Código Genético Único", aboutDesc: "Diseñamos sonrisas personalizadas que armonizan perfectamente con sus facciones.", aboutPoint1: "Cirugía Guiada por Ordenador", aboutPoint1Desc: "Implantes de precisión absoluta sin dolor.", aboutPoint2: "Tecnología CAD/CAM", aboutPoint2Desc: "Carillas en una sola sesión de alta estética.", aboutPoint3: "Examen Microscópico", aboutPoint3Desc: "Procedimientos bajo microscopio dental para máxima seguridad.",
    servicesBadge: "Servicios Dentales Estéticos de Lujo", servicesHeading: "Tecnología de Vanguardia para su Sonrisa", servicesDesc: "Servicios especializados diseñados para la belleza y salud duradera de sus dientes.", service1Title: "Carillas de Zirconio y Lumineers", service1Desc: "Sonrisa Hollywood Smile resistente a manchas y duradera.", service2Title: "Implantes Inmediatos por Computadora", service2Desc: "Reemplace piezas dentales en una sesión sin suturas dolorosas.", service3Title: "Invisalign (Ortodoncia Invisible)", service3Desc: "Alineación cómoda con férulas transparentes e invisibles.", service4Title: "Tratamiento de Encías con Láser", service4Desc: "Estética gingival y desinfección profunda sin dolor.",
    journeyBadge: "Su Guía para una Sonrisa Diamante", journeyHeading: "Un Viaje Cómodo Centrado en el Paciente", journeyStep1: "Diagnóstico Holográfico", journeyStep1Desc: "Modelado 3D de alta precisión.", journeyStep2: "Simulación IA en Vivo", journeyStep2Desc: "Vista previa interactiva de su sonrisa final.", journeyStep3: "Ejecución Quirúrgica Precisa", journeyStep3Desc: "Tratamientos indoloros y rápidos con láser.", journeyStep4: "Sonrisa Nueva y Garantía", journeyStep4Desc: "Suelte su nueva sonrisa respaldada por una garantía médica.",
    baBadge: "Casos Reales de Antes y Después", baHeading: "Pacientes Reales, Obras de Arte", baDesc: "Deslice el marcador central para ver la precisión microscópica de nuestros tratamientos.", baRating: "Cinco Estrellas", baStoryLabel: "Historia del Paciente:",
    baCase1Title: "Carillas de Zirconio Premium", baCase1Desc: "Diseño estético corrigiendo el color y alineación.", baCase1Story: "La paciente presentaba diastemas marcados. Se colocaron 8 carillas de zirconio altamente naturales.", baCase1Type: "Carillas de Zirconio Estéticas", baCase1Duration: "2 sesiones (5 días)",
    baCase2Title: "Implantes Inmediatos de Precisión", baCase2Desc: "Corona fija sobre implante inmediato devolviendo la masticación.", baCase2Story: "Ausencia de diente inferior. Colocación de implante guiado por ordenador en 45 minutos sin dolor.", baCase2Type: "Implante de Titanio Nanostructurado Suizo", baCase2Duration: "1 sesión (2 horas)",
    baCase3Title: "Ortodoncia Invisible Invisalign", baCase3Desc: "Alineación y corrección de apiñamiento de forma cómoda.", baCase3Story: "Apiñamiento severo. En 6 meses se corrigió la alineación mediante Invisalign guiado por IA.", baCase3Type: "Sistema Invisalign 3D Inteligente", baCase3Duration: "6 meses solamente",
    aiBadge: "Diagnóstico Dental Inteligente con IA", aiHeading: "Análisis Inteligente para su", aiHeadingAccent: "Salud Dental y Sonrisa", aiDesc: "Suba una foto de sus dientes para que nuestro sistema analice la salud dental en segundos.", aiUploadTitle: "Suba una Foto de sus Dientes para el Análisis con IA", aiUploadDesc: "Formatos de alta resolución. Use buena iluminación.", aiUploadDrop: "Arrastre su foto aquí o haga clic para elegir", aiCameraBtn: "Tomar Foto (Simulador de Cámara)", aiScanningTitle: "Análisis de IA Activo", aiScanningDesc: "Examinando densidad del esmalte y salud de las encías...", aiScoreLabel: "Puntuación de Salud Dental General", aiScoreStatus: "Excelente y Controlado", aiNewScan: "Nuevo Análisis", aiFindingsTitle: "Hallazgos Detectados (Haga clic para ver):", aiRecsLabel: "Plan Recomendado por la IA:", aiClinicPlan: "Tratamiento Sugerido en Clínica:", aiShareTitle: "Comparta el Reporte con su Dentista", aiShareDesc: "Envíe los resultados a la clínica para agendar su consulta.", aiShareBtn: "Compartir Reporte y Agendar en WhatsApp", aiConf: "Confianza",
    emTitle: "⚠️ ¡Atención Médica Urgente Necesaria!", emDesc: "La IA detectó problemas graves que requieren tratamiento inmediato. Recomendamos agendar cita para evitar complicaciones.", emCtaBook: "Reservar Cita Ahora", emCtaWhatsapp: "Contactar por WhatsApp", emSimulationBtn: "Caso Crítico (Simulación de Emergencia)",
    docBadge: "Médicos Especialistas de Élite", docHeading: "Experiencia Global Dedicada a su Sonrisa", docDesc: "Especialistas egresados de prestigiosas universidades con más de 15 años de trayectoria.", doc1Name: "Dr. Ahmed Hendia", doc1Spec: "Consultor en Odontología Estética e Implantes", doc1Desc: "Líder en diseño digital de sonrisas guiadas por ordenador.", doc2Name: "Dra. Yasmine El Morabit", doc2Spec: "Especialista en Ortodoncia y Cirugía", doc2Desc: "Experta certificada en Invisalign y alineación dental 3D.",
    reviewBadge: "Opiniones de Pacientes", reviewHeading: "Historias Reales de Nuestros Pacientes", review1Text: "¡La mejor tecnología y atención! El resultado de mi sonrisa es increíble y sin dolor.", review2Text: "Las carillas lucen sumamente naturales. Recomiendo totalmente al Dr. Ahmed Hendia.",
    earthBadge: "Ubicación y Soporte Internacional", earthHeading: "Su Sonrisa de Diamante está a su Alcance", earthDesc: "Atendemos pacientes internacionales con traslado de cortesía y estancia de lujo.", earthMapText: "Sede principal: Avenida de las Palmeras, Casablanca, Marruecos",
    blogBadge: "Últimos Avances en Estética Dental", blogHeading: "El Blog Médico Especializado", blogDesc: "Artículos médicos sencillos y consejos escritos por nuestros profesionales.", blogReadMore: "Leer Artículo Completo",
    blogArt1Title: "Diseño 3D CAD/CAM: ¿Cómo Funciona?", blogArt1Desc: "Aprenda cómo fabricamos carillas de precisión en una sola sesión de forma personalizada.", blogArt1Cat: "Tecnología Estética",
    blogArt2Title: "Implantes Sin Cirugía ni Dolor: ¿Verdad o Mito?", blogArt2Desc: "Un análisis sobre las guías digitales que eliminan los cortes y dolor operatorio.", blogArt2Cat: "Cirugía Dental",
    blogArt3Title: "Cómo Elegir Carillas: ¿Zirconio o Lumineers?", blogArt3Desc: "Una comparación clínica completa para ayudarle a tomar la mejor decisión.", blogArt3Cat: "Estética",
    contactBadge: "Portal de Reservas e Inicio de Tratamiento", contactHeading: "Reserve su Cita y Transforme su Sonrisa Hoy", contactDesc: "Complete el formulario para verificar cupos y generar su ticket de ingreso directo.", formName: "Nombre Completo del Paciente", formPhone: "Número Telefónico (con código de país)", formService: "Servicio Solicitado", formServiceSelect: "Seleccione un servicio...", formDate: "Fecha de Preferencia", formBookBtn: "Confirmar Reserva y Generar Ticket", successMsg: "¡Solicitud registrada! Su ticket de ingreso seguro ha sido generado con éxito.", errorMsg: "Por favor complete correctamente todos los campos obligatorios.",
    footerSlogan: "Clínica dental digital de lujo pionera en Oriente Medio, combinando IA y microcirugía guiada.", footerMap: "Mapa del Sitio", footerSupport: "Asuntos Médicos", footerRights: "Todos los Derechos Reservados © 2026 Smile Clínicas Digitales.", footerLabel: "Certificación Internacional 24/7"
  },
  de: {
    navHome: "Startseite", navAbout: "Über uns", navServices: "Dienstleistungen", navBeforeAfter: "Vorher / Nachher", navDoctors: "Ärzte", navContact: "Kontakt", navBookBtn: "Termin buchen", navTitle: "Smile", navSubtitle: "Luxus-Zahnkliniken",
    heroBadge: "Digitale Zahnmedizin & Diamant-Lächeln", heroHeading: "Die Zukunft des Lächelns", heroHeadingAccent: "Mit chirurgischer Präzision", heroDesc: "Die Klinik von Dr. Ahmed Hendia ist die erste im Nahen Osten, die künstliche Intelligenz mit mikroskopischer Implantologie verbindet, für ein perfektes Lächeln ohne Schmerzen.", heroCtaBook: "Reise beginnen", heroCtaAiScan: "Sofortiger KI-Scan",
    statsSatisfied: "Zufriedene Patienten", statsSuccess: "Erfolgsquote bei Operationen", statsSurgeons: "Internationale Experten", statsExperience: "Jahre exzellente Arbeit",
    videoTitle: "Besuchen Sie unser Labor", videoDuration: "Klinik-Video (01:45)",
    aboutBadge: "Hochentwickeltes medizinisches System", aboutHeading: "Klinik Dr. Ahmed Hendia... Ihr Lächeln als genetischer Code", aboutDesc: "Wir erstellen maßgeschneiderte Versorgungen, die perfekt zu Ihren Gesichtszügen passen.", aboutPoint1: "Computergestützte Chirurgie", aboutPoint1Desc: "Präzise Implantate ohne schmerzhafte Schnitte.", aboutPoint2: "CAD/CAM-Technologie", aboutPoint2Desc: "Veneers in nur einer Sitzung in bester Ästhetik.", aboutPoint3: "Mikroskopische Untersuchung", aboutPoint3Desc: "Behandlungen unter dem Operationsmikroskop für maximale Haltbarkeit.",
    servicesBadge: "Luxus-Ästhetische Zahnmedizin", servicesHeading: "Spitzentechnologie für Ihr Lächeln", servicesDesc: "Spezialisierte Behandlungen für Schönheit und lebenslange Gesundheit Ihrer Zähne.", service1Title: "Zirkon-Veneers & Lumineers", service1Desc: "Fleckenresistentes, hochweißes Hollywood-Lächeln.", service2Title: "Computergestützte Sofortimplantate", service2Desc: "Zahnersatz in einer Sitzung ohne schmerzhafte Schnitte.", service3Title: "Invisalign (Unsichtbare Zahnspange)", service3Desc: "Zahnkorrektur mit bequemen, unsichtbaren Schienen.", service4Title: "Gum-Lifting & Laserbehandlung", service4Desc: "Zahnfleischkorrektur und sanfte Desinfektion per Wasserlaser.",
    journeyBadge: "Ihr Weg zum Diamant-Lächeln", journeyHeading: "Ein komfortabler und schmerzfreier Ablauf", journeyStep1: "Holografische Diagnostik", journeyStep1Desc: "Präzises 3D-Modell Ihrer Zähne.", journeyStep2: "Live-KI-Simulation", journeyStep2Desc: "Sofortige Vorschau Ihres Behandlungsziels.", journeyStep3: "Präzise Chirurgie", journeyStep3Desc: "Schmerzfreie Laserbehandlung durch Experten.", journeyStep4: "Neues Lächeln & Garantie", journeyStep4Desc: "Ihr neues Lächeln, abgesichert durch eine Garantiekarte.",
    baBadge: "Echte Vorher-Nachher-Fälle", baHeading: "Echte Patienten, echte Meisterwerke", baDesc: "Verschieben Sie den Regler in der Mitte, um die Präzision unserer Arbeiten zu sehen.", baRating: "Fünf Sterne", baStoryLabel: "Patientenbericht:",
    baCase1Title: "Premium-Zirkon-Veneers", baCase1Desc: "Korrektur von Zahnfarbe und Stellung.", baCase1Story: "Die Patientin litt unter Zahnlücken. 8 hochpräzise Zirkon-Veneers sorgten für ein natürliches Ergebnis.", baCase1Type: "Spektral angepasste Zirkon-Veneers", baCase1Duration: "2 Sitzungen (5 Tage)",
    baCase2Title: "Sofortimplantate mit 3D-Führung", baCase2Desc: "Festsitzender Zahnersatz am gleichen Tag.", baCase2Story: "Verlust eines Unterkieferzahns. Schonendes Einsetzen des Implantats in nur 45 Minuten ohne Schnitte.", baCase2Type: "Schweizer nanostrukturiertes Titan-Implantat", baCase2Duration: "1 Sitzung (2 Stunden)",
    baCase3Title: "Invisalign Unsichtbare Zahnspange", baCase3Desc: "Schonende Zahnkorrektur in kurzer Zeit.", baCase3Story: "Engstand im Frontzahnbereich. Korrektur innerhalb von 6 Monaten durch KI-gestützte Invisalign-Schienen.", baCase3Type: "Mundscansystem Invisalign 3D", baCase3Duration: "Nur 6 Monate",
    aiBadge: "KI-Zahndiagnosezentrum", aiHeading: "Intelligente Sofortanalyse für Ihre", aiHeadingAccent: "Zahngesundheit & Lächeln", aiDesc: "Laden Sie ein Foto Ihrer Zähne hoch, um eine sofortige Analyse Ihrer Zahngesundheit zu erhalten.", aiUploadTitle: "Zahn-Analyse per künstlicher Intelligenz", aiUploadDesc: "Unterstützt hochauflösende Fotos bei guter Beleuchtung.", aiUploadDrop: "Ziehen Sie Ihr Foto hierher oder klicken Sie zur Auswahl", aiCameraBtn: "Foto aufnehmen (Kamerasimulator)", aiScanningTitle: "KI-Diagnose läuft", aiScanningDesc: "Prüfe Schmelzdichte, analysiere Zahnfleisch...", aiScoreLabel: "Zahngesundheits-Score", aiScoreStatus: "Sehr gut & Überwacht", aiNewScan: "Neue Analyse starten", aiFindingsTitle: "Befunde (Klicken für Details):", aiRecsLabel: "KI-Empfehlungen:", aiClinicPlan: "Empfohlener Therapieplan:", aiShareTitle: "Bericht mit Arzt teilen", aiShareDesc: "Senden Sie die Ergebnisse an die Klinik, um Ihren Termin abzustimmen.", aiShareBtn: "Bericht senden & Termin buchen via WhatsApp", aiConf: "Sicherheit",
    emTitle: "⚠️ Dringender Handlungsbedarf festgestellt!", emDesc: "Die KI hat schwerwiegende Probleme erkannt. Bitte vereinbaren Sie umgehend einen Termin, um Komplikationen zu vermeiden.", emCtaBook: "Jetzt Termin buchen", emCtaWhatsapp: "Via WhatsApp kontaktieren", emSimulationBtn: "Kritischer Fall (Notfall-Simulation)",
    docBadge: "Medizinische Spezialisten", docHeading: "Globale Kompetenz für Ihr Lächeln", docDesc: "Ärzte mit Ausbildung an führenden internationalen Universitäten und über 15 Jahren Erfahrung.", doc1Name: "Dr. Ahmed Hendia", doc1Spec: "Spezialist für ästhetische Zahnheilkunde & Implantologie", doc1Desc: "Führender Experte für computergestütztes Smile-Design.", doc2Name: "Dr. Yasmine El Morabit", doc2Spec: "Fachzahnärztin für Kieferorthopädie", doc2Desc: "Zertifizierte Expertin für Invisalign und 3D-Zahnkorrektur.",
    reviewBadge: "Patientenberichte", reviewHeading: "Echte Geschichten unserer Patienten", review1Text: "Hervorragende Technologie und Zuwendung! Das Ergebnis meines neuen Lächelns ist perfekt und absolut schmerzfrei.", review2Text: "Die Veneers sehen unglaublich natürlich aus. Ich kann Dr. Ahmed Hendia wärmstens empfehlen.",
    earthBadge: "Standort & Auslandsservice", earthHeading: "Ihr neues Lächeln ist erreichbar", earthDesc: "Wir betreuen internationale Patienten inklusive Flughafen-Transfer und Luxushotel.", earthMapText: "Hauptsitz: Palm Avenue, Casablanca, Marokko",
    blogBadge: "Aktuelles aus der Zahnästhetik", blogHeading: "Der spezialisierte medizinische Blog", blogDesc: "Fachartikel und Tipps unserer Experten für Ihre Zahngesundheit.", blogReadMore: "Artikel lesen",
    blogArt1Title: "3D CAD/CAM Smile-Design: Wie funktioniert es?", blogArt1Desc: "Erfahren Sie, wie wir individuelle Kronen und Veneers in einer Sitzung präzise fertigen.", blogArt1Cat: "Ästhetische Technik",
    blogArt2Title: "Schmerzfreie Implantate ohne OP: Wahrheit oder Mythos?", blogArt2Desc: "Ein Blick auf 3D-Schablonen, die Schnitte und postoperative Schmerzen verhindern.", blogArt2Cat: "Zahnchirurgie",
    blogArt3Title: "Zirkon oder Lumineers: Welche Veneers passen?", blogArt3Desc: "Ein clinical Vergleich der Materialien zur Unterstützung Ihrer Entscheidung.", blogArt3Cat: "Ästhetik",
    contactBadge: "Buchungsportal & Terminplaner", contactHeading: "Buchen Sie Ihren Termin und starten Sie heute", contactDesc: "Tragen Sie Ihre Daten ein. Unser System prüft freie Zeiten und erstellt Ihr Ticket.", formName: "Vollständiger Name des Patienten", formPhone: "Telefonnummer (mit Vorwahl)", formService: "Gewünschte Behandlung", formServiceSelect: "Bitte wählen...", formDate: "Wunschtermin", formBookBtn: "Termin buchen & Ticket erstellen", successMsg: "Terminanfrage erfolgreich gesendet! Ihr Ticket wurde erstellt.", errorMsg: "Bitte füllen Sie alle Pflichtfelder korrekt aus.",
    footerSlogan: "Führende digitale Zahnklinik im Nahen Osten, die KI mit computergestützter Mikrochirurgie kombiniert.", footerMap: "Sitemap", footerSupport: "Medizinische Abteilung", footerRights: "Alle Rechte vorbehalten © 2026 Smile Digitale Kliniken.", footerLabel: "Internationale Zertifizierung 24/7"
  },
  it: {
    navHome: "Home", navAbout: "Chi Siamo", navServices: "Servizi", navBeforeAfter: "Prima / Dopo", navDoctors: "Medici", navContact: "Contatti", navBookBtn: "Prenota Ora", navTitle: "Smile", navSubtitle: "Cliniche Dentali di Lusso",
    heroBadge: "Rivoluzione Dentale Digitale & Sorriso di Diamante", heroHeading: "Il Futuro del Design del Sorriso", heroHeadingAccent: "Con Precisione Chirurgica", heroDesc: "La clinica del Dr. Ahmed Hendia è la prima in Medio Oriente ad integrare l'intelligenza artificiale con l'implantologia microscopica per un sorriso perfetto senza dolore.", heroCtaBook: "Inizia il Viaggio", heroCtaAiScan: "Scansione IA Istantanea",
    statsSatisfied: "Pazienti che Sorridono", statsSuccess: "Percentuale di Successo Chirurgico", statsSurgeons: "Chirurghi Esperti Internazionali", statsExperience: "Anni di Eccellenza Medica",
    videoTitle: "Visita il Nostro Laboratorio", videoDuration: "Video Clinica (01:45)",
    aboutBadge: "Sistema Medico Avanzato", aboutHeading: "Clinica Dr. Ahmed Hendia... Il tuo sorriso come codice genetico unico", aboutDesc: "Progettiamo sorrisi personalizzati che si armonizzano perfettamente con il tuo viso.", aboutPoint1: "Chirurgia Guidata dal Computer", aboutPoint1Desc: "Impianti precisi al 100% senza tagli dolorosi.", aboutPoint2: "Tecnologia CAD/CAM", aboutPoint2Desc: "Faccette in una sola seduta di altissima estetica.", aboutPoint3: "Esame Microscopico", aboutPoint3Desc: "Trattamenti eseguiti sotto microscopio per massima sicurezza.",
    servicesBadge: "Servizi Dentali Estetici di Lusso", servicesHeading: "Tecnologia all'Avanguardia per il tuo Sorriso", servicesDesc: "Trattamenti esclusivi per la bellezza e la salute dei tuoi denti.", service1Title: "Faccette in Zirconio e Lumineers", service1Desc: "Sorriso Hollywood Smile brillante e resistente alle macchie.", service2Title: "Impianti Immediati Guidati", service2Desc: "Sostituzione denti in una seduta senza dolori operatori.", service3Title: "Invisalign (Ortodonzia Invisibile)", service3Desc: "Allineamento confortevole con mascherine trasparenti.", service4Title: "Tratamento Gengive con Laser", service4Desc: "Estetica gengivale e disinfezione profonda indolore.",
    journeyBadge: "La tua Guida al Sorriso Diamante", journeyHeading: "Un Percorso Confortevole Centrato su di Te", journeyStep1: "Diagnostica Holografica", journeyStep1Desc: "Modellazione 3D ad alta precisione.", journeyStep2: "Simulazione IA in Diretta", journeyStep2Desc: "Anteprima interattiva del tuo sorriso.", journeyStep3: "Esecuzione Chirurgica Precisa", journeyStep3Desc: "Trattamenti rapidi e indolori con laser.", journeyStep4: "Nuovo Sorriso e Garanzia", journeyStep4Desc: "Sorriso nuovo protetto da certificato di garanzia.",
    baBadge: "Casi Reali di Prima e Dopo", baHeading: "Pazienti Reali, Capolavori Reali", baDesc: "Trascina il cursore per vedere la precisione microscopica dei nostri trattamenti.", baRating: "Cinque Stelle", baStoryLabel: "Storia del Paziente:",
    baCase1Title: "Faccette in Zirconio Premium", baCase1Desc: "Design estetico con correzione di colore e allineamento.", baCase1Story: "La paziente soffriva di diastemi evidenti. Applicate 8 faccette in zirconio ultra-naturali.", baCase1Type: "Faccette in Zirconio Estetiche", baCase1Duration: "2 sedute (5 giorni)",
    baCase2Title: "Impianti Immediati di Precisione 3D", baCase2Desc: "Corona fissa su impianto immediato senza incisioni dolorose.", baCase2Story: "Perdita dente inferiore. Inserimento impianto guidato in 45 minuti senza punti.", baCase2Type: "Implant in Titanio Nanostrutturato Svizzero", baCase2Duration: "1 seduta (2 ore)",
    baCase3Title: "Ortodoncia Invisibile Invisalign", baCase3Desc: "Allineamento rapido e invisibile in tempi record.", baCase3Story: "Affollamento dentale grave. Corretto in 6 mesi con mascherine Invisalign guidate da IA.", baCase3Type: "Sistema Invisalign 3D Avanzato", baCase3Duration: "Solo 6 mesi",
    aiBadge: "Diagnosi Dentale Intelligente con IA", aiHeading: "Analisi Intelligente per la tua", aiHeadingAccent: "Salute Dentale e Sorriso", aiDesc: "Carica una foto dei tuoi denti per un'analisi immediata del tuo sorriso tramite IA.", aiUploadTitle: "Analisi Dentale Avanzata con IA", aiUploadDesc: "Carica foto ad alta risoluzione con buona luminosità.", aiUploadDrop: "Trascina la foto qui o clicca per selezionare", aiCameraBtn: "Scatta Foto (Simulatore Fotocamera)", aiScanningTitle: "Diagnostica IA Attiva", aiScanningDesc: "Analizzando smalto e salute gengivale...", aiScoreLabel: "Punteggio di Salute Dentale", aiScoreStatus: "Eccellente e Monitorato", aiNewScan: "Nuova Analisi", aiFindingsTitle: "Problemi Rilevati (Clicca per dettagli):", aiRecsLabel: "Raccomandazioni IA:", aiClinicPlan: "Trattamento Clinico Suggerito:", aiShareTitle: "Condividi il Report con il Medico", aiShareDesc: "Invia i risultati alla clinica per fissare la visita.", aiShareBtn: "Condividi Report e Prenota su WhatsApp", aiConf: "Sicurezza",
    emTitle: "⚠️ Attenzione! Necessario Intervento Urgente", emDesc: "L'IA ha rilevato problemi gravi. Consigliamo di prenotare subito una visita per evitare complicazioni.", emCtaBook: "Prenota Ora la Visita", emCtaWhatsapp: "Contatta via WhatsApp", emSimulationBtn: "Caso Critico (Simulazione d'Urgenza)",
    docBadge: "Medici Specialisti d'Élite", docHeading: "Esperienza Globale Dedicata al tuo Sorriso", docDesc: "Specialisti formati nelle migliori università con oltre 15 anni di carriera.", doc1Name: "Dr. Ahmed Hendia", doc1Spec: "Consulente in Odontoiatria Estetica e Impianti", doc1Desc: "Leader nel design digitale di sorrisi guidati da computer.", doc2Name: "Dr.ssa Yasmine El Morabit", doc2Spec: "Specialista in Ortodonzia e Chirurgia", doc2Desc: "Esperta Invisalign e allineamento dentale 3D.",
    reviewBadge: "Recensioni Pazienti", reviewHeading: "Storie Reali dei Nostri Pazienti", review1Text: "Tecnologia e attenzione eccezionali! Il mio nuovo sorriso è perfetto e senza dolore.", review2Text: "Faccette fantastiche ed estremamente naturali. Raccomando caldamente il Dr. Ahmed Hendia.",
    earthBadge: "Sede & Supporto Internazionale", earthHeading: "Il Sorriso dei tuoi Sogni è Vicino", earthDesc: "Accogliamo pazienti internazionali con transfert gratuito e soggiorno di lusso.", earthMapText: "Sede principale: Via delle Palme, Casablanca, Marocco",
    blogBadge: "Ultimi Aggiornamenti in Odontoiatria", blogHeading: "Il Blog Medico Specialized", blogDesc: "Articoli medici informativi scritti dai nostri professionisti.", blogReadMore: "Leggi Articolo Completo",
    blogArt1Title: "Design 3D CAD/CAM: Come Funziona?", blogArt1Desc: "Scopri come creiamo faccette di precisione personalizzate in una sola seduta.", blogArt1Cat: "Tecnologia Estetica",
    blogArt2Title: "Impianti Senza Dolore e Senza Tagli: Realtà o Mito?", blogArt2Desc: "Un'analisi sulle guide digitali 3D che eliminano dolori e gonfiore post-operatorio.", blogArt2Cat: "Chirurgia Dentale",
    blogArt3Title: "Come Scegliere le Faccette: Zirconio o Lumineers?", blogArt3Desc: "Una panoramica completa per aiutarti a scegliere il trattamento ideale.", blogArt3Cat: "Estetica",
    contactBadge: "Portale Prenotazioni e Trattamento", contactHeading: "Prenota la tua Visita e Inizia Oggi", contactDesc: "Compila il modulo per verificare le disponibilità e ricevere il tuo pass d'accesso.", formName: "Nome Completo Paziente", formPhone: "Numero di Telefono (con prefisso)", formService: "Servizio Richiesto", formServiceSelect: "Seleziona servizio...", formDate: "Data Preferita", formBookBtn: "Conferma Prenonazione e Genera Pass", successMsg: "Richiesta registrata! Il pass d'accesso sicuro è stato generato con successo.", errorMsg: "Compila correttamente tutti i campi obbligatori.",
    footerSlogan: "Clinica odontoiatrica digitale d'eccellenza che unisce IA e chirurgia guidata 3D.", footerMap: "Mappa del Sito", footerSupport: "Affari Medici", footerRights: "Tutti i Diritti Riservati © 2026 Smile Cliniche Digitali.", footerLabel: "Certificazione Internazionale 24/7"
  },
  pt: {
    navHome: "Início", navAbout: "Sobre Nós", navServices: "Serviços", navBeforeAfter: "Antes / Depois", navDoctors: "Médicos", navContact: "Contacto", navBookBtn: "Reservar Consulta", navTitle: "Smile", navSubtitle: "Clínicas Dentárias de Luxo",
    heroBadge: "Revolução Dentária Digital & Sorriso de Diamante", heroHeading: "O Futuro do Design de Sorrisos", heroHeadingAccent: "Com Precisão Cirúrgica", heroDesc: "A clínica do Dr. Ahmed Hendia é la primeira no Médio Oriente a integrar inteligência artificial para um sorriso perfeito sem dor.", heroCtaBook: "Iniciar Viagem", heroCtaAiScan: "Análise Instantânea com IA",
    statsSatisfied: "Pacientes Sorridentes", statsSuccess: "Taxa de Sucesso em Cirurgias", statsSurgeons: "Cirurgiões Especialistas", statsExperience: "Anos de Excelência Médica",
    videoTitle: "Visite o Nosso Laboratório", videoDuration: "Vídeo Clínica (01:45)",
    aboutBadge: "Sistema Médico Ultra Avançado", aboutHeading: "Clínica Dr. Ahmed Hendia... O seu sorriso como código genético único", aboutDesc: "Desenhamos sorrisos personalizados que harmonizam perfeitamente com o seu rosto.", aboutPoint1: "Cirurgia Guiada por Computador", aboutPoint1Desc: "Implantes de precisão sem dor.", aboutPoint2: "Tecnologia CAD/CAM", aboutPoint2Desc: "Facetas em apenas uma sessão de alta estética.", aboutPoint3: "Exame Microscópico", aboutPoint3Desc: "Procedimentos sob microscópio para total segurança.",
    servicesBadge: "Serviços Dentários Estéticos de Luxo", servicesHeading: "Tecnologia de Ponta para o seu Sorriso", servicesDesc: "Tratamentos especializados para beleza e saúde dentária de longa duração.", service1Title: "Facetas de Zircónio e Lumineers", service1Desc: "Sorriso Hollywood Smile resistente a manchas e super brilhante.", service2Title: "Implantes Imediatos Guiados", service2Desc: "Substituição dentária em uma sessão sem dores operatorias.", service3Title: "Invisalign (Alinhadores Invisíveis)", service3Desc: "Alinhamento confortável com moldeiras transparentes.", service4Title: "Tratamento de Gengivas a Laser", service4Desc: "Estética gengival e desinfeção profunda e indolor.",
    journeyBadge: "O seu Guia para o Sorriso Diamante", journeyHeading: "Uma Jornada Confortável Focada em Si", journeyStep1: "Diagnóstico Holográfico", journeyStep1Desc: "Modelação 3D de alta precisão.", journeyStep2: "Simulação IA ao Vivo", journeyStep2Desc: "Visualização interativa do seu sorriso.", journeyStep3: "Execução Cirúrgica de Precisão", journeyStep3Desc: "Tratamentos a laser rápidos e indolores.", journeyStep4: "Novo Sorriso e Garantia", journeyStep4Desc: "Sorriso novo protegido por garantia médica.",
    baBadge: "Casos Reais de Antes e Depois", baHeading: "Pacientes Reais, Obras de Arte", baDesc: "Arraste o cursor central para ver a precisão microscópica das nossas facetas.", baRating: "Cinco Estrelas", baStoryLabel: "História do Paciente:",
    baCase1Title: "Facetas de Zircónio Premium", baCase1Desc: "Design estético com correção de cor e alinhamento.", baCase1Story: "A paciente sofria de espaçamento pronunciado. Colocámos 8 facetas de zircónio ultra-naturais.", baCase1Type: "Facetas de Zircónio Estéticas", baCase1Duration: "2 sessões (5 dias)",
    baCase2Title: "Implantes Imediatos de Precisão 3D", baCase2Desc: "Coroa fixa sobre implante imediato sem dores e sem cortes.", baCase2Story: "Perda de dente inferior. Colocação de implante em 45 minutos sem suturas.", baCase2Type: "Implant de Titânio Nanocristalino Suíço", baCase2Duration: "1 sessão (2 horas)",
    baCase3Title: "Ortodontia Invisível Invisalign", baCase3Desc: "Alinhamento e correção de apinhamento de forma invisível.", baCase3Story: "Apinhamento severo. Em 6 meses corrigido com alinhadores Invisalign e acompanhamento de IA.", baCase3Type: "Sistema Invisalign 3D Inteligente", baCase3Duration: "Apenas 6 meses",
    aiBadge: "Análise Dentária Avançada com IA", aiHeading: "Análise Inteligente para a sua", aiHeadingAccent: "Saúde Dentária e Sorriso", aiDesc: "Carregue uma foto dos seus dentes para um diagnóstico rápido e completo do seu sorriso via IA.", aiUploadTitle: "Diagnóstico Dental com Inteligência Artificial", aiUploadDesc: "Suporta fotos em alta resolução com boa iluminação.", aiUploadDrop: "Arraste a foto aqui ou clique para selecionar", aiCameraBtn: "Tirar Foto (Simulador de Câmara)", aiScanningTitle: "Diagnóstico de IA Ativo", aiScanningDesc: "Examinando esmalte e gengivas...", aiScoreLabel: "Pontuação de Saúde Dentária", aiScoreStatus: "Excelente e Monitorizado", aiNewScan: "Nova Análise", aiFindingsTitle: "Problemas Detetados (Clique para detalhes):", aiRecsLabel: "Plano Recomendado pela IA:", aiClinicPlan: "Tratamento Clínico Sugerido:", aiShareTitle: "Partilhe o Relatório com o Médico", aiShareDesc: "Envie os resultados para a clínica para agendar a consulta.", aiShareBtn: "Partilhar Relatório e Reservar via WhatsApp", aiConf: "Segurança",
    emTitle: "⚠️ Atenção! Intervenção Urgente Requerida", emDesc: "A IA detetou problemas graves. Recomendamos marcar consulta o mais rápido possível para evitar complicações.", emCtaBook: "Marcar Consulta Agora", emCtaWhatsapp: "Contactar via WhatsApp", emSimulationBtn: "Caso Crítico (Simulação de Emergência)",
    docBadge: "Médicos Especialistas de Elite", docHeading: "Experiencia Global Dedicada ao seu Sorriso", docDesc: "Especialistas graduados nas melhores faculdades com mais de 15 anos de percurso.", doc1Name: "Dr. Ahmed Hendia", doc1Spec: "Consultor em Odontologia Estética e Implantes", doc1Desc: "Líder em design digital de sorrisos assistidos por computador.", doc2Name: "Dr.a Yasmine El Morabit", doc2Spec: "Especialista em Ortodontia e Cirurgia", doc2Desc: "Especialista certificada Invisalign e alinhamento dental 3D.",
    reviewBadge: "Opiniões de Pacientes", reviewHeading: "Histórias Reais dos Nossos Pacientes", review1Text: "Tecnologia e carinho ímpares! O resultado final é fantástico e totalmente indolor.", review2Text: "As facetas parecem dentes naturais. Recomendo muito o Dr. Ahmed Hendia.",
    earthBadge: "Localização & Apoio Internacional", earthHeading: "O Sorriso dos seus Sonhos está ao seu Alcance", earthDesc: "Apoiamos pacientes internacionais com transporte privado e estadia de luxo.", earthMapText: "Sede principal: Avenida das Palmeiras, Casablanca, Marrocos",
    blogBadge: "Últimas Novidades na Estética Dentária", blogHeading: "O Blog Médico Especializado", blogDesc: "Artigos científicos simples escritos por profissionais da saúde.", blogReadMore: "Ler Artigo Completo",
    blogArt1Title: "Design 3D CAD/CAM: Como Funciona?", blogArt1Desc: "Aprenda como fabricamos facetas e coroas de precisão em apenas uma sessão.", blogArt1Cat: "Tecnologia Estética",
    blogArt2Title: "Implantes Sem Dor e Sem Cirurgia: Realidade ou Mito?", blogArt2Desc: "Uma análise médica de como as guias 3D evitam cortes dolorosos.", blogArt2Cat: "Cirurgia Dental",
    blogArt3Title: "Como Escolher Facetas: Zircónio ou Lumineers?", blogArt3Desc: "Guia clínico completo detalhando as diferenças estruturais.", blogArt3Cat: "Estética",
    contactBadge: "Portal de Reservas e Consultas", contactHeading: "Marque a sua Consulta e Transforme o seu Sorriso", contactDesc: "Preencha o formulário para agendar o seu horário e gerar o pass de entrada.", formName: "Nome Completo do Paciente", formPhone: "Número de Telefone (com indicativo)", formService: "Serviço Solicitado", formServiceSelect: "Selecione um serviço...", formDate: "Data Preferencial", formBookBtn: "Confirmar Reserva e Criar Ticket", successMsg: "Solicitação registada! O seu ticket de acesso seguro foi gerado.", errorMsg: "Por favor preencha todos os campos obrigatórios corretamente.",
    footerSlogan: "Clínica dentária digital de luxo pioneira, aliando IA a cirurgia guiada por computador.", footerMap: "Mapa do Site", footerSupport: "Assuntos Médicos", footerRights: "Todos os Direitos Reservados © 2026 Smile Clínicas Digitais.", footerLabel: "Certificação Internacional 24/7"
  },
  tr: {
    navHome: "Ana Sayfa", navAbout: "Hakkımızda", navServices: "Hizmetler", navBeforeAfter: "Önce / Sonra", navDoctors: "Hekimler", navContact: "İletişim", navBookBtn: "Randevu Al", navTitle: "Smile", navSubtitle: "Lüks Diş Klinikleri",
    heroBadge: "Dijital Diş Hekimliği Devrimi & Elmas Gülüş", heroHeading: "Gülüş Tasarımının Geleceği", heroHeadingAccent: "Cerrahi Hassasiyetle", heroDesc: "Dr. Ahmed Hendia kliniği, mükemmel bir gülüşü acısız bir şekilde sunmak için yapay zekayı mikroskobik diş implantolojisiyle birleştiren lider kliniktir.", heroCtaBook: "Yolculuğa Başla", heroCtaAiScan: "Anında Yapay Zeka Taraması",
    statsSatisfied: "Güvenle Gülümseyen Hastalar", statsSuccess: "Zorlu Ameliyatlarda Başarı Oranı", statsSurgeons: "Uluslararası Uzman Hekimler", statsExperience: "Yıllık Tıbbi ve Akademik Deneyim",
    videoTitle: "Futuristik Laboratuvarımızı Ziyaret Edin", videoDuration: "Klinik Videosu (01:45)",
    aboutBadge: "Gelişmiş Tıbbi Sistem", aboutHeading: "Dr. Ahmed Hendia Kliniği... Genetik Kodunuz Kadar Benzersiz Bir Gülüş", aboutDesc: "Hazır şablonlar uygulamıyoruz; yüz şeklinizi ve çene yapınızı inceleyerek size özel gülüş tasarlıyoruz.", aboutPoint1: "Bilgisayar Güdümlü Cerrahi", aboutPoint1Desc: "Ağrısız ve dikişsiz %100 hassas implantlar.", aboutPoint2: "CAD/CAM Teknolojisi", aboutPoint2Desc: "Tek seansta hazırlanan son derece estetik laminalar.", aboutPoint3: "Mikroskobik Muayene", aboutPoint3Desc: "Maksimum dayanıklılık için mikroskop altında tedaviler.",
    servicesBadge: "Lüks Estetik Diş Hekimliği Hizmetleri", servicesHeading: "Gülüşünüz İçin En Yeni Çözümler", servicesDesc: "Dişlerinizin sağlığı ve güzelliği için titizlikle tasarlanmış uzman tedaviler.", service1Title: "Zirkonyum Laminalar & Lumineers", service1Desc: "Leke tutmayan, kalıcı Hollywood Smile gülüşü.", service2Title: "Bilgisayar Destekli Hızlı İmplant", service2Desc: "Ağrısız tek seansta diş eksikliklerinin tamamlanması.", service3Title: "Invisalign (Şeffaf Plak Tedavisi)", service3Desc: "Görünmeyen şeffaf plaklarla konforlu diş düzeltme.", service4Title: "Lazerle Diş Eti Tedavisi & Şekillendirme", service4Desc: "Su lazeri ile diş eti estetiği ve ağrısız sterilizasyon.",
    journeyBadge: "Elmas Gülüş Rehberiniz", journeyHeading: "Sizin İçin Tasarlanmış Rahat Bir Tedavi Süreci", journeyStep1: "Holografik Teşhis", journeyStep1Desc: "Yüksek hassasiyetli 3D modelleme.", journeyStep2: "Canlı Yapay Zeka Simülasyonu", journeyStep2Desc: "Tedavi sonundaki gülüşünüzün anlık önizlemesi.", journeyStep3: "Hassas Cerrahi Uygulama", journeyStep3Desc: "Uzmanlar tarafından ağrısız ve hızlı lazer tedavileri.", journeyStep4: "Yeni Gülüş ve Garanti", journeyStep4Desc: "Garanti sertifikalı, yepyeni mükemmel bir gülüş.",
    baBadge: "Gerçek Önce / Sonra Tedavi Örnekleri", baHeading: "Gerçek Hastalar, Gerçek Sanat Eserleri", baDesc: "Çalışmalarımızın hassasiyetini görmek için ortadaki kaydırıcıyı sürükleyin.", baRating: "Beş Yıldız", baStoryLabel: "Hasta Hikayesi:",
    baCase1Title: "Premium Zirkonyum Laminalar", baCase1Desc: "Renk ve diş hizalamasını düzelten estetik gülüş tasarımı.", baCase1Story: "Hasta diş aralarındaki açıklıklardan şikayetçiydi. Son derece doğal 8 adet zirkonyum lamina uygulandı.", baCase1Type: "Estetik Zirkonyum Laminalar", baCase1Duration: "2 seans (5 gün)",
    baCase2Title: "Güdümlü Güvenli İmplantlar", baCase2Desc: "Ağrısız dikişsiz yöntemle aynı gün sabit kuron.", baCase2Story: "Alt çene diş kaybı. Bilgisayar destekli tarama ile 45 dakikada dikişsiz implant.", baCase2Type: "İsviçre Nanoyapılı Titanyum İmplant", baCase2Duration: "1 seans (2 saat)",
    baCase3Title: "Invisalign Şeffaf Ortodonti", baCase3Desc: "Şeffaf plaklar ile konforlu ve görünmez diş hizalama.", baCase3Story: "Ciddi diş çapraşıklığı. Yapay zeka destekli Invisalign plaklarıyla 6 ayda düzeltildi.", baCase3Type: "Akıllı Invisalign 3D Sistemi", baCase3Duration: "Sadece 6 ay",
    aiBadge: "Yapay Zeka Destekli Diş Teşhis Merkezi", aiHeading: "Ağız Sağlığınız ve Gülüşünüz İçin", aiHeadingAccent: "Anında Yapay Zeka Taraması", aiDesc: "Yapay zeka analizimizle dişlerinizin sağlık durumunu anında öğrenmek için fotoğraf yükleyin.", aiUploadTitle: "Yapay Zeka ile Diş Sağlığı Analizi", aiUploadDesc: "İyi aydınlatılmış, yüksek çözünürlüklü fotoğraflar yükleyin.", aiUploadDrop: "Fotoğrafı buraya sürükleyin veya seçmek için tıklayın", aiCameraBtn: "Fotoğraf Çek (Kamera Simülatörü)", aiScanningTitle: "Yapay Zeka Analizi Aktif", aiScanningDesc: "Mine yoğunluğu inceleniyor, diş eti sağlığı analiz ediliyor...", aiScoreLabel: "Genel Diş Sağlığı Puanı", aiScoreStatus: "Mükemmel ve Takip Altında", aiNewScan: "Yeni Analiz", aiFindingsTitle: "Tespit Edilen Bulgular (Detaylar için tıklayın):", aiRecsLabel: "Yapay Zeka Önerileri:", aiClinicPlan: "Önerilen Tedavi Planı:", aiShareTitle: "Raporu Hekimle Paylaş", aiShareDesc: "Randevunuzu planlamak için sonuçları kliniğimize gönderin.", aiShareBtn: "Raporu Paylaş ve WhatsApp Üzerinden Kaydol", aiConf: "Güvenirlik",
    emTitle: "⚠️ Acil Diş Müdahalesi Gerekiyor!", emDesc: "Yapay zeka acil müdahale gerektiren ciddi problemler tespit etti. Komplikasyonları önlemek için hemen randevu almanızı öneririz.", emCtaBook: "Hemen Randevu Al", emCtaWhatsapp: "WhatsApp'tan İletişime Geç", emSimulationBtn: "Kritik Durum (Acil Durum Simülasyonu)",
    docBadge: "Seçkin Uzman Hekimler ve Cerrahlar", docHeading: "Gülüşünüze Adanmış Küresel Deneyim", docDesc: "Prestijli uluslararası üniversitelerden mezun, 15+ yıl deneyimli hekim kadromuz.", doc1Name: "Dr. Ahmed Hendia", doc1Spec: "Mikroskobik Diş Hekimliği ve İmplantoloji Uzmanı", doc1Desc: "Bilgisayar destekli estetik gülüş tasarımında öncü uzman.", doc2Name: "Dr. Yasmine El Morabit", doc2Spec: "Ortodonti ve Çene Cerrahisi Uzmanı", doc2Desc: "Invisalign ve 3D çene hizalama konusunda uluslararası sertifikalı hekim.",
    reviewBadge: "Hasta Yorumları", reviewHeading: "Hastalarımızın Gerçek İyileşme Hikayeleri", review1Text: "Harika teknoloji ve ilgi! Yeni gülüşümün sonucu kusursuz ve kesinlikle ağrısız.", review2Text: "Laminalar o kadar doğal görünüyor ki, herkes nereden yaptırdığımı soruyor. Teşekkürler Dr. Hendia!",
    earthBadge: "Konum & Uluslararası Hizmet", earthHeading: "Hayalinizdeki Gülüşe Ulaşmak Çok Kolay", earthDesc: "Yurtdışından gelen hastalarımıza özel lüks transfer ve konaklama sağlıyoruz.", earthMapText: "Merkez Ofis: Palmiye Caddesi, Kazablanka, Fas",
    blogBadge: "Diş Estetiğindeki Son Gelişmeler", blogHeading: "Uzman Tıbbi Blogumuz", blogDesc: "Uzmanlarımız tarafından kaleme alınan diş sağlığı makaleleri.", blogReadMore: "Yazının Tamamını Oku",
    blogArt1Title: "3D CAD/CAM Gülüş Tasarımı Nasıl Yapılır?", blogArt1Desc: "Yüz hatlarınıza en uygun laminate ve kuronları tek seansta nasıl hazırladığımızı keşfedin.", blogArt1Cat: "Estetik Teknoloji",
    blogArt2Title: "Ağrısız ve Ameliyatsız İmplantlar: Gerçek mi Efsane mi?", blogArt2Desc: "Cerrahi kesi ve ağrıları ortadan kaldıran dijital şablonlara tıbbi bakış.", blogArt2Cat: "Cerrahi Tedavi",
    blogArt3Title: "Laminate Tercihi: Zirkonyum mu Lumineers mi?", blogArt3Desc: "Gülüşünüz için en doğru kararı vermenize yardımcı olacak klinik karşılaştırma.", blogArt3Cat: "Estetik",
    contactBadge: "Randevu Portalı & Takvim", contactHeading: "Randevunuzu Ayarlayın ve Bugün Başlayın", contactDesc: "Bilgilerinizi girin. Sistemimiz müsait saatleri kontrol edip giriş biletinizi oluşturacaktır.", formName: "Hastanın Tam Adı", formPhone: "Telefon Numarası (Ülke kodu ile)", formService: "Talep Edilen Tedavi Alanı", formServiceSelect: "Lütfen seçiniz...", formDate: "Tercih Edilen Randevu Tarihi", formBookBtn: "Randevuyu Onayla ve Bilet Oluştur", successMsg: "Talebiniz alındı! Güvenli randevu biletiniz başarıyla oluşturuldu.", errorMsg: "Lütfen tüm zorunlu alanları doğru şekilde doldurun.",
    footerSlogan: "Yapay zeka ve bilgisayar destekli mikrocerrahiyi birleştiren lüks dijital diş kliniği.", footerMap: "Site Haritası", footerSupport: "Tıbbi İşler", footerRights: "Tüm Hakları Saklıdır © 2026 Smile Dijital Klinikleri.", footerLabel: "Uluslararası Sertifikasyon 24/7"
  },
  ru: {
    navHome: "Главная", navAbout: "О нас", navServices: "Услуги", navBeforeAfter: "До / После", navDoctors: "Врачи", navContact: "Контакты", navBookBtn: "Запись на прием", navTitle: "Smile", navSubtitle: "Стоматологические клиники люкс",
    heroBadge: "Революция цифровой стоматологии и бриллиантовая улыбка", heroHeading: "Будущее дизайна улыбки", heroHeadingAccent: "С хирургической точностью", heroDesc: "Клиника доктора Ахмеда Хендиа — первая на Ближнем Востоке, объединившая ИИ с микроскопической имплантологией, обеспечивая идеальную улыбку без боли.", heroCtaBook: "Начать путешествие", heroCtaAiScan: "Быстрый ИИ-анализ",
    statsSatisfied: "Пациентов улыбаются уверенно", statsSuccess: "Успешность сложных операций", statsSurgeons: "Врачи мирового класса", statsExperience: "Лет медицинского превосходства",
    videoTitle: "Посетите нашу лабораторию", videoDuration: "Видео о клинике (01:45)",
    aboutBadge: "Высокотехнологичная медицина", aboutHeading: "Клиника д-ра Хендиа... Ваша улыбка как уникальный генетический код", aboutDesc: "Мы изучаем структуру лица и зубов, чтобы создать улыбку, гармонирующую с вашим образом.", aboutPoint1: "Навигационная имплантация", aboutPoint1Desc: "Установка имплантатов под цифровым контролем без боли и разрезов.", aboutPoint2: "Технологии CAD/CAM", aboutPoint2Desc: "Изготовление премиальных виниров за один визит с максимальной естественностью.", aboutPoint3: "Микроскобическое лечение", aboutPoint3Desc: "Лечение каналов и реставрация под микроскопом для долговечности.",
    servicesBadge: "Услуги премиальной эстетической стоматологии", servicesHeading: "Новые технологии для вашей улыбки", servicesDesc: "Специализированные услуги, созданные для красоты и здоровья ваших зубов.", service1Title: "Виниры из диоксида циркония и люминиры", service1Desc: "Идеально белая улыбка Hollywood Smile, устойчивая к окрашиванию.", service2Title: "Одномоментная имплантация по шаблону", service2Desc: "Восстановление зубов за один сеанс без болезненных надрезов.", service3Title: "Invisalign (Невидимые элайнеры)", service3Desc: "Эстетичное выравнивание прозрачными съемными капами.", service4Title: "Лечение и пластика десен лазером", service4Desc: "Коррекция десневой улыбки и бережная лазерная дезинфекция без боли.",
    journeyBadge: "Ваш путь к бриллиантовой улыбке", journeyHeading: "Комфортный лечебный процесс для каждого", journeyStep1: "Цифровая 3D-диагностика", journeyStep1Desc: "Точнейшее моделирование прикуса.", journeyStep2: "Онлайн-ИИ-моделирование", journeyStep2Desc: "Моментальный просмотр финального результата.", journeyStep3: "Бережное вмешательство", journeyStep3Desc: "Безболезненное лазерное лечение экспертами.", journeyStep4: "Новая улыбка и гарантия", journeyStep4Desc: "Ваша улыбка с медицинским гарантийным сертификатом.",
    baBadge: "Реальные случаи До и После", baHeading: "Реальные пациенты, реальные шедевры", baDesc: "Передвигайте бегунок, чтобы оценить микроскопическую точность наших реставраций.", baRating: "Пять Звезд", baStoryLabel: "История пациента:",
    baCase1Title: "Циркониевые виниры премиум-класса", baCase1Desc: "Коррекция оттенка и восстановление ровного зубного ряда.", baCase1Story: "Пациентка обратилась по поводу щелей между зубами. Установлено 8 циркониевых виниров.", baCase1Type: "Эстетичные циркониевые виниры", baCase1Duration: "2 визита (5 дней)",
    baCase2Title: "Навигационная экспресс-имплантация", baCase2Desc: "Установка коронки на имплантат в день обращения.", baCase2Story: "Потеря зуба нижней челюсти. Имплантация по 3D-шаблону выполнена за 45 минут без разрезов.", baCase2Type: "Швейцарский наноструктурированный титановый имплантат", baCase2Duration: "1 визит (2 часа)",
    baCase3Title: "Элайнеры Invisalign", baCase3Desc: "Выравнивание зубов комфортным и незаметным способом.", baCase3Story: "Сильная скученность зубов. За 6 месяцев положение зубов исправлено благодаря ИИ Invisalign.", baCase3Type: "Умная система элайнеров Invisalign 3D", baCase3Duration: "Всего 6 месяцев",
    aiBadge: "Диагностический ИИ-центр стоматологии", aiHeading: "Интеллектуальный анализ вашей", aiHeadingAccent: "Зубной здоровья и улыбки", aiDesc: "Загрузите фото зубов, чтобы получить мгновенный анализ здоровья полости рта от ИИ.", aiUploadTitle: "ИИ-диагностика здоровья зубов", aiUploadDesc: "Поддерживает фото высокого разрешения. Пожалуйста, делайте фото при хорошем свете.", aiUploadDrop: "Перетащите фото сюда или нажмите для выбора", aiCameraBtn: "Сделать фото (Симулятор камеры)", aiScanningTitle: "ИИ-анализ активен", aiScanningDesc: "Проверка плотности эмали, оценка состояния десен...", aiScoreLabel: "Оценка здоровья полости рта", aiScoreStatus: "Отлично и под наблюдением", aiNewScan: "Начать новый анализ", aiFindingsTitle: "Обнаруженные проблемы (Кликните для деталей):", aiRecsLabel: "Рекомендации ИИ:", aiClinicPlan: "Рекомендуемый план лечения:", aiShareTitle: "Поделиться отчетом с врачом", aiShareDesc: "Отправьте результаты в клинику для записи на прием.", aiShareBtn: "Отправить отчет и записаться через WhatsApp", aiConf: "Точность",
    emTitle: "⚠️ Требуется срочное медицинское вмешательство!", emDesc: "ИИ обнаружил серьезные проблемы. Настоятельно рекомендуем записаться на прием во избежание осложнений.", emCtaBook: "Записаться прямо сейчас", emCtaWhatsapp: "Связаться в WhatsApp", emSimulationBtn: "Критический случай (Симуляция тревоги)",
    docBadge: "Выдающиеся врачи и хирурги", docHeading: "Мировой опыт на службе вашей улыбки", docDesc: "Специалисты с образованием в ведущих мировых вузах и опытом более 15 лет.", doc1Name: "Д-р Ахмед Хендиа", doc1Spec: "Консультант по микроскопической и имплантационной стоматологии", doc1Desc: "Ведущий эксперт по компьютерному дизайну улыбки.", doc2Name: "Д-р Ясмин Эль Морабит", doc2Spec: "Специалист по ортодонтии и хирургии", doc2Desc: "Сертифицированный эксперт по Invisalign и 3D-коррекции прикуса.",
    reviewBadge: "Отзывы пациентов", reviewHeading: "Реальные истории лечения наших пациентов", review1Text: "Потрясающая клиника и технологии! Результат превзошел все ожидания, совсем не больно.", review2Text: "Виниры выглядят потрясающе естественно. Буду рекомендовать доктора Ахмеда всем друзьям.",
    earthBadge: "Контакты & Международный сервис", earthHeading: "Ваша идеальная улыбка ближе, чем кажется", earthDesc: "Для иностранных пациентов предоставляем трансфер из аэропорта и роскошное проживание.", earthMapText: "Главный офис: Пальмовый проспект, Касабланка, Марокко",
    blogBadge: "Последние достижения эстетической стоматологии", blogHeading: "Специализированный медицинский блог", blogDesc: "Простые и понятные статьи от наших врачей о здоровье ваших зубов.", blogReadMore: "Читать статью полностью",
    blogArt1Title: "3D CAD/CAM дизайн улыбки: как это работает?", blogArt1Desc: "Узнайте, как мы изготавливаем коронки и виниры за один сеанс с микронной точностью.", blogArt1Cat: "Эстетичные технологии",
    blogArt2Title: "Имплантация без разрезов и боли: правда или вымысел?", blogArt2Desc: "Разбор того, как навигационные 3D-шаблоны избавляют от боли и отеков после операции.", blogArt2Cat: "Хирургическое лечение",
    blogArt3Title: "Как выбрать виниры: диоксид циркония или люминиры?", blogArt3Desc: "Подробное сравнение материалов, которое поможет сделать правильный выбор.", blogArt3Cat: "Эстетика",
    contactBadge: "Запись на прием и календарь консультаций", contactHeading: "Забронируйте визит и начните сегодня", contactDesc: "Введите ваши данные. Наша система проверит доступное время и создаст пропуск.", formName: "Полное имя пациента", formPhone: "Номер телефона (с кодом страны)", formService: "Желаемая услуга", formServiceSelect: "Выберите услугу...", formDate: "Предпочтительная дата", formBookBtn: "Подтвердить запись и создать билет", successMsg: "Заявка принята! Ваш персональный пропуск успешно создан.", errorMsg: "Пожалуйста, заполните все обязательные поля корректно.",
    footerSlogan: "Премиальный стоматологический центр, объединяющий ИИ и микрохирургию под контролем компьютера.", footerMap: "Карта сайта", footerSupport: "Медицинский отдел", footerRights: "Все права защищены © 2026 Smile Цифровые Клиники.", footerLabel: "Международная сертификация 24/7"
  },
  zh: {
    navHome: "首页", navAbout: "关于我们", navServices: "医疗服务", navBeforeAfter: "对比案例", navDoctors: "医疗团队", navContact: "联系预约", navBookBtn: "立即预约", navTitle: "Smile", navSubtitle: "尊贵奢华数字牙科",
    heroBadge: "数字牙科革命与钻石美齿设计", heroHeading: "微笑美学设计的未来", heroHeadingAccent: "精准计算机显微导航", heroDesc: "Dr. Ahmed Hendia 诊所是中东首家将人工智能与显微种植、美学修复完美融合的专业牙科机构，确保您在无痛中拥有完美笑容。", heroCtaBook: "立即开启旅程", heroCtaAiScan: "人工智能即时测齿",
    statsSatisfied: "拥有自信微笑的客户", statsSuccess: "复杂手术临床成功率", statsSurgeons: "国际顶尖医学专家", statsExperience: "年卓越医疗与科研沉淀",
    videoTitle: "点击视频，探访数字化无菌实验室", videoDuration: "诊所介绍视频 (01:45)",
    aboutBadge: "超前沿医疗技术体系", aboutHeading: "Dr. Ahmed Hendia 诊所... 微笑如同独一无二的基因密码", aboutDesc: "我们拒绝千篇一律的模板，深度研究面部美学比例与双唇动态，定制完全契合您的专属笑容。", aboutPoint1: "计算机导航微创种植", aboutPoint1Desc: "100%精准数字化导板，避开神经与血管，无痛、无需传统切口。", aboutPoint2: "CAD/CAM 即刻修复", aboutPoint2Desc: "精确定制牙冠或瓷贴面，单次就诊即可佩戴，呈现极致通透自然美感。", aboutPoint3: "高分辨显微治疗", aboutPoint3Desc: "在专业牙科显微镜下进行根管及充填治疗，确保极致安全与长久耐用。",
    servicesBadge: "奢华牙齿美学修复方案", servicesHeading: "尖端数字化设备，匠心雕琢美齿", servicesDesc: "针对高标准客户，设计融美学、舒适性与长久耐用为一体的专属方案。", service1Title: "超薄瓷贴面、超瓷及全瓷冠", service1Desc: "轻松拥有通透洁白、高硬度不染色的好莱坞钻石微笑。", service2Title: "数字化微创即刻种植牙", service2Desc: "单次就诊即可完成拔牙与种植重建，免除漫长等待与手术创伤。", service3Title: "Invisalign 隐形矫治 (隐形牙套)", service3Desc: "采用定制式高分子透明膜卡，舒适美观，自由摘戴，悄然排齐牙齿。", service4Title: "水激光牙龈修整及色素去除", service4Desc: "利用无痛温柔的水激光改善露龈笑，恢复娇嫩牙龈健康色泽。",
    journeyBadge: "钻石美牙四部曲", journeyHeading: "科学、舒适、愉悦的数字化尊享旅程", journeyStep1: "3D数字化全景扫描", journeyStep1Desc: "采集高清晰度口腔CT与照片，精准重建面部骨骼及牙齿3D数字模型。", journeyStep2: "人工智能美学即时设计", journeyStep2Desc: "大模型结合美学数据，即时渲染最终笑容效果，让您在术前亲眼见证效果。", journeyStep3: "专家微创无痛精细执行", journeyStep3Desc: "由资深硕博专家团队主导，配备无痛激光设备，极速、安全、舒适。", journeyStep4: "终身保障与舒心复查", journeyStep4Desc: "绽放自信微笑，提供全方位品质质保书，畅享终身贴心追踪维护服务。",
    baBadge: "真实治疗前后对比案例", baHeading: "真实患者，完美微笑蜕变", baDesc: "左右滑动中间的亮光滑块，观摩微笑设计的显微级匹配度和微米级细节。", baRating: "五星好评", baStoryLabel: "患者故事：",
    baCase1Title: "臻品氧化锆奢华瓷贴面", baCase1Desc: "调整双颌咬合，完美修复重度四环素牙、氟斑牙及牙齿缝隙。", baCase1Story: "患者因严重前牙缝隙和色素沉着而失去笑容自信。通过定制8颗超通透全瓷贴面，重建面部美学比例，效果极致自然。", baCase1Type: "光谱高透全锆超薄贴面", baCase1Duration: "2次就诊 (5天)",
    baCase2Title: "数字化导航即刻种植牙", baCase2Desc: "单颗/多颗缺失牙即刻重建，无需开刀，即刻恢复咬合功能。", baCase2Story: "下颌第一磨牙因龋坏缺失。采用数字化导板进行无痛种植，手术仅历时45分钟，无需切开和缝合，术后即可进食。", baCase2Type: "瑞士纳米结构高强度纯钛种植体", baCase2Duration: "1次就诊 (2小时)",
    baCase3Title: "Invisalign 隐形正畸系统", baCase3Desc: "以隐形、美观、舒适的方式快速排齐拥挤不齐的前牙。", baCase3Story: "上下前牙重度拥挤且伴有深覆合。采用先进的隐形矫治方案，在人工智能实时监控下，仅历时6个月即达到完美整齐排齐。", baCase3Type: "Invisalign 3D数字化隐形牙套", baCase3Duration: "仅需6个月",
    aiBadge: "人工智能口腔测齿诊断中心", aiHeading: "即时智能检测您的", aiHeadingAccent: "口腔健康与微笑指数", aiDesc: "进入未来感十足的全息口腔诊断实验室。上传一张牙齿照片，我们的医疗超级大模型将瞬间完成健康扫描，生成专业分析报告。", aiUploadTitle: "上传牙齿照片，开启AI智能扫描", aiUploadDesc: "支持高清JPG/PNG格式。请在充足光线下正对拍摄双颌，避免阴影遮挡。", aiUploadDrop: "将照片拖拽至此处，或点击浏览选择文件", aiCameraBtn: "即时拍照 (相机模拟器)", aiScanningTitle: "人工智能正在诊断中", aiScanningDesc: "正在评估牙釉质密度、分析牙龈健康度并智能匹配诊疗建议...", aiScoreLabel: "口腔健康综合评分", aiScoreStatus: "健康状况良好，需定期维护", aiNewScan: "重新扫描", aiFindingsTitle: "AI 智能筛查结果 (点击以聚焦查看)：", aiRecsLabel: "人工智能精准护理建议：", aiClinicPlan: "建议在诊所进行的治疗项目：", aiShareTitle: "将您的口腔报告一键发给医生", aiShareDesc: "您可以将即时测齿结果发送至诊所，一键快捷预约名医面诊及专业评估方案。", aiShareBtn: "发送报告并一键预约 (WhatsApp)", aiConf: "置信度",
    emTitle: "⚠️ 警告：口腔健康亮起红灯，需即刻就诊！", emDesc: "AI口腔大模型检测到您的牙齿存在重度病变或隐性隐患，建议立即预约医生，以免错失最佳治疗时机。", emCtaBook: "立即预约面诊", emCtaWhatsapp: "联系WhatsApp客服", emSimulationBtn: "上传严重病例 (紧急情况模拟)",
    docBadge: "国际硕博专家及种植大师团队", docHeading: "卓越医疗水准，全心呵护微笑", docDesc: "我们的医学专家均毕业于欧美名校，拥有15年以上临床及科研经验，是行业知名学术带头人。", doc1Name: "Dr. Ahmed Hendia", doc1Spec: "显微美学修复及种植首席专家", doc1Desc: "数字化微创种植倡导者，专注高端大案及计算机辅助微笑定制。", doc2Name: "Dr. Yasmine El Morabit", doc2Spec: "隐形正畸及颌骨畸形矫正专家", doc2Desc: "隐形牙套资深特聘专家，擅长面部美学、咬合及隐形牙套正畸。",
    reviewBadge: "海内外患者倾心好评", reviewHeading: "倾听他们重获自信微笑的故事", review1Text: "老实说，我从未体验过如此高科技且贴心的服务！贴面效果极其逼真，治疗全程真的没有痛感，极力推荐！", review2Text: "这是摩洛哥及中东最专业的诊所。做完贴面后大家都夸我很自然，大赞 Ahmed Hendia 医生！",
    earthBadge: "黄金地理位置与尊贵接送礼遇", earthHeading: "无论您身处何方，美丽笑容触手切及", earthDesc: "我们为从海湾国家及欧洲专程而来的尊贵客户，提供全流程私人机场接送及五星级酒店奢华住宿代订安排。", earthMapText: "总部地址：摩洛哥卡萨布兰卡 Palm Avenue 3层",
    blogBadge: "掌握全球口腔前沿科技风向标", blogHeading: "名医大讲堂：专业牙科科普与指南", blogDesc: "由我们资深名医撰写的口腔科普，分享护齿常识，助您长久拥有健康迷人的钻石微笑。", blogReadMore: "阅读全文",
    blogArt1Title: "CAD/CAM 3D即刻美学修复：科技如何颠覆传统？", blogArt1Desc: "揭秘我们如何在单次就诊中，运用三维扫描和微米级精细雕刻，制作出完全贴合您面部特征的全瓷贴面。", blogArt1Cat: "修复前沿科技",
    blogArt2Title: "无创无痛种植牙：是真实黑科技还是商业宣传？", blogArt2Desc: "深度解析数字化导板如何避开面部神经，避免开刀与缝合，实现当天种牙、当天即刻负重进食。", blogArt2Cat: "微创种植技术",
    blogArt3Title: "全瓷贴面避坑指南：氧化锆和超薄贴面怎么选？", blogArt3Desc: "为您梳理硬度、通透度及适应证等核心维度的差异，帮助您为美牙做出最科学理性的选择。", blogArt3Cat: "美学修复",
    contactBadge: "名医面诊及数字建档预约通道", contactHeading: "今天做出改变，定制您的无暇微笑", contactDesc: "请在下方填入基本就诊信息，我们的智能建档系统将一键锁定预约档期，并即时为您发放诊所专属通行证。", formName: "患者姓名 (中文/英文)", formPhone: "联系电话 (请带上国家区号)", formService: "咨询就诊项目", formServiceSelect: "请选择咨询项目...", formDate: "期望面诊日期", formBookBtn: "一键提交预约并生成数字通行证", successMsg: "您的面诊预约申请已成功提交！您的数字化专属通行证已生成，客服将尽快与您核对日程。", errorMsg: "请正确填写所有必填信息，以确保成功建立数字化就诊档案。",
    footerSlogan: "中东首屈一指的数字化尊奢牙科中心，致力于利用人工智能与显微计算机导航手术，重塑生命笑容与自然美学。", footerMap: "站点地图", footerSupport: "医疗品质监控", footerRights: "版权所有 © 2026 Smile 数字化口腔连锁医院。", footerLabel: "国际权威认证，24小时在线为您守护"
  }
};
